"""
SQL 终结符
"""

import enum

import metasequoia_parser as ms_parser

__all__ = [
    "SqlTerminalType"
]


@enum.unique
class SqlTerminalType(ms_parser.symbol.TerminalType):
    """终结符类型的枚举类"""

    # 解析器系统符号
    SYSTEM_END_OF_INPUT = 0  # INTERNAL : 词法解析器解析结束
    SYSTEM_ABORT = 57  # INTERNAL : 词法解析器解析异常

    # 解析指定语法标记
    GRAMMAR_EXPRESSION = 58  # 解析表达式
    GRAMMAR_FIELD_TYPE = 59  # 解析字段类型

    # 优先级标记符号
    KEYWORD_USED_AS_IDENT = 4
    KEYWORD_USED_AS_KEYWORD = 5
    CONDITIONLESS_JOIN = 6
    NEG = 7
    SUBQUERY_AS_EXPR = 8
    EMPTY_FROM_CLAUSE = 9

    # 单字节运算符
    OPERATOR_PLUS = 10  # OPERATOR : +
    OPERATOR_CARET = 11  # OPERATOR : ^
    OPERATOR_TILDE = 12  # OPERATOR : ~
    OPERATOR_PERCENT = 13  # OPERATOR : %
    OPERATOR_SUB = 14  # OPERATOR : -
    OPERATOR_LT = 15  # OPERATOR : <
    OPERATOR_GT = 16  # OPERATOR : >
    OPERATOR_EQ = 17  # OPERATOR : =
    OPERATOR_STAR = 18  # OPERATOR : *
    OPERATOR_SLASH = 19  # OPERATOR : /
    OPERATOR_BANG = 20  # OPERATOR : !
    OPERATOR_AMP = 21  # OPERATOR : &
    OPERATOR_BAR = 22  # OPERATOR : |
    OPERATOR_COLON = 23  # OPERATOR : :
    OPERATOR_LPAREN = 24  # OPERATOR : (
    OPERATOR_RPAREN = 25  # OPERATOR : )
    OPERATOR_COMMA = 26  # OPERATOR : ,
    OPERATOR_LBRACE = 27  # OPERATOR : {
    OPERATOR_RBRACE = 28  # OPERATOR : }
    OPERATOR_DOT = 29  # OPERATOR : .
    OPERATOR_AT = 30  # OPERATOR : @
    OPERATOR_SEMICOLON = 31  # OPERATOR : ;
    OPERATOR_DOLLAR = 32  # OPERATOR : $

    # 多字节运算符
    OPERATOR_AMP_AMP = 33  # OPERATOR : &&
    OPERATOR_LT_EQ_GT = 34  # OPERATOR : <=>
    OPERATOR_GT_EQ = 35  # OPERATOR : >=
    OPERATOR_LT_EQ = 36  # OPERATOR : <=
    OPERATOR_BANG_EQ = 37  # OPERATOR : <> 或 !=
    OPERATOR_BAR_BAR = 38  # OPERATOR : ||
    OPERATOR_LT_LT = 39  # OPERATOR : <<
    OPERATOR_GT_GT = 40  # OPERATOR : >>
    OPERATOR_SUB_GT = 41  # OPERATOR: ->
    OPERATOR_SUB_GT_GT = 42  # OPERATOR: ->>
    OPERATOR_COLON_EQ = 43  # OPERATOR: :=

    # 字面值
    LITERAL_BIN_NUM = 44  # 二进制字面值（仅包含二进制数部分）
    LITERAL_HEX_NUM = 45  # 十六进制字面值（仅包含十六进制数部分）
    LITERAL_DECIMAL_NUM = 46  # 不包含 e 或 E 的小数字面值
    LITERAL_FLOAT_NUM = 47  # 包含 e 或 E 的浮点数字面值
    LITERAL_INT_NUM = 48  # 整数字面值（在 Python 中不再区分 3 种整型）
    LITERAL_NCHAR_STRING = 49  # unicode 字符串字面值
    LITERAL_TEXT_STRING = 50  # 字符串字面值
    LITERAL_UNDERSCORE_CHARSET = 51  # 下划线开头的字符集名称

    # 标识符
    IDENT = 52  # 标识符
    IDENT_QUOTED = 53  # 包含括号的标识符

    # 特殊元素
    LEX_HOSTNAME = 54  # @ 之后的 Token
    PARAM_MARKER = 55  # ? 开头的参数值
    DOLLAR_QUOTED_STRING = 56  # $$ ... $$

    # 关键字
    KEYWORD_ACCESSIBLE = 60  # reserved keyword
    KEYWORD_ACCOUNT = 61  # keyword
    KEYWORD_ACTION = 62  # keyword : SQL-2003-N
    KEYWORD_ACTIVE = 63  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_ADD = 64  # reserved keyword : SQL-2003-R
    KEYWORD_ADDDATE = 65  # word : MYSQL-FUNC
    KEYWORD_ADMIN = 66  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_AFTER = 67  # keyword : SQL-2003-N
    KEYWORD_AGAINST = 68  # keyword
    KEYWORD_AGGREGATE = 69  # keyword
    KEYWORD_ALGORITHM = 70  # keyword
    KEYWORD_ALL = 71  # reserved keyword : SQL-2003-R
    KEYWORD_ALTER = 72  # reserved keyword : SQL-2003-R
    KEYWORD_ALWAYS = 73  # keyword
    KEYWORD_ANALYZE = 74  # keyword
    KEYWORD_AND = 75  # reserved keyword : SQL-2003-R
    KEYWORD_ANY = 76  # keyword : SQL-2003-R
    KEYWORD_ARRAY = 77  # keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_AS = 78  # reserved keyword : SQL-2003-R
    KEYWORD_ASC = 79  # reserved keyword : SQL-2003-N
    KEYWORD_ASCII = 80  # keyword : MYSQL-FUNC
    KEYWORD_ASENSITIVE = 81  # reserved keyword : FUTURE-USE
    KEYWORD_AT = 82  # keyword : SQL-2003-R
    KEYWORD_ATTRIBUTE = 83  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_AUTHENTICATION = 84  # keyword (MySQL 8.0)
    KEYWORD_AUTO_INC = 85  # keyword
    KEYWORD_AUTOEXTEND_SIZE = 86  # keyword
    KEYWORD_AUTO_INCREMENT = 87  # keyword
    KEYWORD_AVG = 88  # keyword : SQL-2003-N
    KEYWORD_AVG_ROW_LENGTH = 89  # keyword
    KEYWORD_BACKUP = 90  # keyword
    KEYWORD_BEFORE = 91  # reserved keyword : SQL-2003-N
    KEYWORD_BEGIN = 92  # keyword : SQL-2003-R
    KEYWORD_BERNOULLI = 93  # keyword
    KEYWORD_BETWEEN = 94  # reserved keyword : SQL-2003-R
    KEYWORD_BIGINT = 95  # reserved keyword : SQL-2003-R
    KEYWORD_BINARY = 96  # reserved keyword : SQL-2003-R
    KEYWORD_BINLOG = 97  # keyword
    KEYWORD_BIT = 98  # keyword : MYSQL-FUNC
    KEYWORD_BLOB = 99  # reserved keyword : SQL-2003-R
    KEYWORD_BLOCK = 100  # keyword
    KEYWORD_BOOL = 101  # keyword
    KEYWORD_BOOLEAN = 102  # keyword : SQL-2003-R
    KEYWORD_BOTH = 103  # reserved keyword : SQL-2003-R
    KEYWORD_BTREE = 104  # keyword
    KEYWORD_BUCKETS = 105  # keyword (MySQL 8.0)
    KEYWORD_BULK = 106  # keyword (MySQL 8.0)
    KEYWORD_BY = 107  # reserved keyword : SQL-2003-R
    KEYWORD_BYTE = 108  # keyword
    KEYWORD_CACHE = 109  # keyword
    KEYWORD_CALL = 110  # reserved keyword : SQL-2003-R
    KEYWORD_CASCADE = 111  # reserved keyword : SQL-2003-N
    KEYWORD_CASCADED = 112  # keyword : SQL-2003-R
    KEYWORD_CASE = 113  # reserved keyword : SQL-2003-R
    KEYWORD_CATALOG_NAME = 114  # keyword : SQL-2003-N
    KEYWORD_CHAIN = 115  # keyword : SQL-2003-N
    KEYWORD_CHALLENGE_RESPONSE = 116  # keyword (MySQL 8.0)
    KEYWORD_CHANGE = 117  # reserved keyword
    KEYWORD_CHANGED = 118  # keyword
    KEYWORD_CHANNEL = 119  # keyword
    KEYWORD_CHAR = 120  # reserved keyword : SQL-2003-R
    KEYWORD_CHARACTER = 121  # reserved keyword
    KEYWORD_CHARSET = 122  # keyword
    KEYWORD_CHECK = 123  # reserved keyword : SQL-2003-R
    KEYWORD_CHECKSUM = 124  # keyword
    KEYWORD_CIPHER = 125  # keyword
    KEYWORD_CLASS_ORIGIN = 126  # keyword : SQL-2003-N
    KEYWORD_CLIENT = 127  # keyword
    KEYWORD_CLONE = 128  # keyword (MySQL 8.0)
    KEYWORD_CLOSE = 129  # keywrod : SQL-2003-R
    KEYWORD_COALESCE = 130  # keyword : SQL-2003-N
    KEYWORD_CODE = 131  # keyword
    KEYWORD_COLLATE = 132  # reserved keyword : SQL-2003-R
    KEYWORD_COLLATION = 133  # keyword : SQL-2003-N
    KEYWORD_COLUMN = 134  # reserved keyword : SQL-2003-R
    KEYWORD_COLUMNS = 135  # keyword
    KEYWORD_COLUMN_FORMAT = 136  # keyword
    KEYWORD_COLUMN_NAME = 137  # keyword : SQL-2003-N
    KEYWORD_COMMENT = 138  # keyword
    KEYWORD_COMMIT = 139  # keyowrd : SQL-2003-R
    KEYWORD_COMMITTED = 140  # keyword : SQL-2003-N
    KEYWORD_COMPACT = 141  # keyword
    KEYWORD_COMPLETION = 142  # keyword
    KEYWORD_COMPONENT = 143  # keyword (MySQL 8.0)
    KEYWORD_COMPRESSED = 144  # keyword
    KEYWORD_COMPRESSION = 145  # keyword
    KEYWORD_CONCURRENT = 146  # keyword
    KEYWORD_CONDITION = 147  # reserved keyword : SQL-2003-R, SQL-2008-R
    KEYWORD_CONNECTION = 148  # keyword
    KEYWORD_CONSISTENT = 149  # keyword
    KEYWORD_CONSTRAINT = 150  # reserved keyword : SQL-2003-R
    KEYWORD_CONSTRAINT_CATALOG = 151  # keyword : SQL-2003-N
    KEYWORD_CONSTRAINT_NAME = 152  # keyword : SQL-2003-N
    KEYWORD_CONSTRAINT_SCHEMA = 153  # keyword : SQL-2003-N
    KEYWORD_CONTAINS = 154  # keyword : SQL-2003-N
    KEYWORD_CONTEXT = 155  # keyword
    KEYWORD_CONTINUE = 156  # reserved keyword : SQL-2003-R
    KEYWORD_CONVERT = 157  # reserved keyword : SQL-2003-N
    KEYWORD_CPU = 158  # keyword
    KEYWORD_CREATE = 159  # reserved keyword : SQL-2003-R
    KEYWORD_CROSS = 160  # reserved keyword : SQL-2003-R
    KEYWORD_CUBE = 161  # reserved keyword : SQL-2003-R
    KEYWORD_CUME_DIST = 162  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_CURRENT = 163  # keyword : SQL-2003-R
    KEYWORD_CURRENT_DATE = 164  # reserved keyword
    KEYWORD_CURRENT_TIME = 165  # reserved keyword
    KEYWORD_CURRENT_TIMESTAMP = 166  # reserved keyword
    KEYWORD_CURRENT_USER = 167  # reserved keyword : SQL-2003-R
    KEYWORD_CURSOR = 168  # reserved keyword : SQL-2003-R
    KEYWORD_CURSOR_NAME = 169  # keyword : SQL-2003-N
    KEYWORD_DATA = 170  # keyword : SQL-2003-N
    KEYWORD_DATABASE = 171  # reserved keyword
    KEYWORD_DATABASES = 172  # reserved keyword
    KEYWORD_DATAFILE = 173  # keyword
    KEYWORD_DATE = 174  # keyword : SQL-2003-R
    KEYWORD_DATETIME = 175  # keyword
    KEYWORD_DAY = 176  # keyword : SQL-2003-R
    KEYWORD_DAY_HOUR = 177  # reserved keyword
    KEYWORD_DAY_MICROSECOND = 178  # reserved keyword
    KEYWORD_DAY_MINUTE = 179  # reserved keyword
    KEYWORD_DAY_SECOND = 180  # reserved keyword
    KEYWORD_DEALLOCATE = 181  # keyword : SQL-2003-R
    KEYWORD_DEC = 182  # reserved keyword
    KEYWORD_DECIMAL = 183  # reserved keyword : SQL-2003-R
    KEYWORD_DECLARE = 184  # reserved keyword : SQL-2003-R
    KEYWORD_DEFAULT = 185  # reserved keyword : SQL-2003-R
    KEYWORD_DEFAULT_AUTH = 186  # keyword : INTERNAL
    KEYWORD_DEFINER = 187  # keyword
    KEYWORD_DEFINITION = 188  # keyword (MySQL 8.0)
    KEYWORD_DELAYED = 189  # reserved keyword
    KEYWORD_DELAY_KEY_WRITE = 190  # keyword
    KEYWORD_DELETE = 191  # reserved keyword : SQL-2003-R
    KEYWORD_DENSE_RANK = 192  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_DESC = 193  # reserved keyword : SQL-2003-N
    KEYWORD_DESCRIBE = 194  # reserved keyword : SQL-2003-R
    KEYWORD_DESCRIPTION = 195  # keyword (MySQL 8.0)
    KEYWORD_DETERMINISTIC = 196  # reserved keyword : SQL-2003-R
    KEYWORD_DIAGNOSTICS = 197  # keyword : SQL-2003-N
    KEYWORD_DIRECTORY = 198  # keyword
    KEYWORD_DISABLE = 199  # keyword
    KEYWORD_DISCARD = 200  # keyword : MYSQL
    KEYWORD_DISK = 201  # keyword
    KEYWORD_DISTINCT = 202  # reserved keyowrd : SQL-2003-R
    KEYWORD_DISTINCTROW = 203  # reserved keyowrd
    KEYWORD_DIV = 204  # reserved keyword
    KEYWORD_DO = 205  # keyword
    KEYWORD_DOUBLE = 206  # reserved keyowrd : SQL-2003-R
    KEYWORD_DROP = 207  # reserved keyowrd : SQL-2003-R
    KEYWORD_DUAL = 208  # reserved keyword
    KEYWORD_DUMPFILE = 209  # keyword
    KEYWORD_DUPLICATE = 210  # keyword
    KEYWORD_DYNAMIC = 211  # keyword : SQL-2003-R
    KEYWORD_EACH = 212  # reserved keyword: SQL-2003-R
    KEYWORD_ELSE = 213  # reserved keyword: SQL-2003-R
    KEYWORD_ELSEIF = 214  # reserved keyword
    KEYWORD_EMPTY = 215  # reserved keyword: SQL-2016-R (MySQL 8.0)
    KEYWORD_ENABLE = 216  # keyword
    KEYWORD_ENCLOSED = 217  # reserved keyword
    KEYWORD_ENCRYPTION = 218  # keyword
    KEYWORD_END = 219  # keyword : SQL-2003-R
    KEYWORD_ENDS = 220  # keyword
    KEYWORD_ENFORCED = 221  # keyword : SQL-2015-N (MySQL 8.0)
    KEYWORD_ENGINE = 222  # keyword
    KEYWORD_ENGINES = 223  # keyword
    KEYWORD_ENGINE_ATTRIBUTE = 224  # Keyword : MYSQL (MySQL 8.0)
    KEYWORD_ENUM = 225  # keyword : MYSQL
    KEYWORD_ERROR = 226  # keyword
    KEYWORD_ERRORS = 227  # keyword
    KEYWORD_ESCAPE = 228  # keyword : SQL-2003-R
    KEYWORD_ESCAPED = 229  # reserved keyword
    KEYWORD_EVENT = 230  # keyword
    KEYWORD_EVENTS = 231  # keyword
    KEYWORD_EVERY = 232  # keyword : SQL-2003-N
    KEYWORD_EXCEPT = 233  # reserved keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_EXCHANGE = 234  # keyword
    KEYWORD_EXCLUDE = 235  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_EXECUTE = 236  # keyword : SQL-2003-R
    KEYWORD_EXISTS = 237  # reserved keyword : SQL-2003-R
    KEYWORD_EXIT = 238  # reserved keyword
    KEYWORD_EXPANSION = 239  # keyword
    KEYWORD_EXPIRE = 240  # keyword
    KEYWORD_EXPLAIN = 241  # reserved keyword
    KEYWORD_EXPORT = 242  # keyword
    KEYWORD_EXTENDED = 243  # keyword
    KEYWORD_EXTENT_SIZE = 244  # keyword
    KEYWORD_FACTOR = 245  # keyword (MySQL 8.0)
    KEYWORD_FAILED_LOGIN_ATTEMPTS = 246  # keyword (MySQL 8.0)
    KEYWORD_FALSE = 247  # reserved keyword : SQL-2003-R
    KEYWORD_FAST = 248  # keyword
    KEYWORD_FAULTS = 249  # keyword
    KEYWORD_FETCH = 250  # reserved keyword : SQL-2003-R
    KEYWORD_FIELDS = 251  # keyword
    KEYWORD_FILE = 252  # keyword
    KEYWORD_FILE_BLOCK_SIZE = 253  # keyword
    KEYWORD_FILTER = 254  # keyword
    KEYWORD_FINISH = 255  # keyword : SQL-2016-N (MySQL 8.0)
    KEYWORD_FIRST = 256  # keyword : SQL-2003-N
    KEYWORD_FIRST_VALUE = 257  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_FIXED = 258  # keyword
    KEYWORD_FLOAT = 259  # reserved keyword : SQL-2003-R
    KEYWORD_FLOAT4 = 260  # reserved keyword
    KEYWORD_FLOAT8 = 261  # reserved keyword
    KEYWORD_FLUSH = 262  # keyword
    KEYWORD_FOLLOWING = 263  # keyowrd : SQL-2003-N (MySQL 8.0)
    KEYWORD_FOLLOWS = 264  # keyword : MYSQL
    KEYWORD_FOR = 265  # reserved keyword : SQL-2003-R
    KEYWORD_FORCE = 266  # reserved keyword
    KEYWORD_FOREIGN = 267  # reserved keyword : SQL-2003-R
    KEYWORD_FORMAT = 268  # keyword
    KEYWORD_FOUND = 269  # keyword : SQL-2003-R
    KEYWORD_FROM = 270  # reserved keyword
    KEYWORD_FULL = 271  # keyword : SQL-2003-R
    KEYWORD_FULLTEXT = 272  # reserved keyword
    KEYWORD_FUNCTION = 273  # reserved keyword : SQL-2003-R
    KEYWORD_GENERAL = 274  # keyword
    KEYWORD_GENERATE = 275  # keyword (MySQL 8.0)
    KEYWORD_GENERATED = 276  # keyword
    KEYWORD_GEOMCOLLECTION = 277  # reserved keyword
    KEYWORD_GEOMETRY = 278  # keyword
    KEYWORD_GEOMETRYCOLLECTION = 279  # keyword : MYSQL
    KEYWORD_GET = 280  # reserved keyword : SQL-2003-R
    KEYWORD_GET_MASTER_PUBLIC_KEY = 281  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_GET_FORMAT = 282  # keyword : MYSQL-FUNC
    KEYWORD_GET_SOURCE_PUBLIC_KEY = 283  # keyword (MySQL 8.0)
    KEYWORD_GLOBAL = 284  # keyword : SQL-2003-R
    KEYWORD_GRANT = 285  # reserved keyword : SQL-2003-R
    KEYWORD_GRANTS = 286  # keyword
    KEYWORD_GROUP = 287  # reserved keyword : SQL-2003-R
    KEYWORD_GROUPING = 288  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_GROUPS = 289  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_GROUP_REPLICATION = 290  # keyword
    KEYWORD_GTIDS = 291  # keyword (MySQL 8.0)
    KEYWORD_GTID_ONLY = 292  # keyword (MySQL 8.0)
    KEYWORD_HANDLER = 293  # keyword
    KEYWORD_HASH = 294  # keyword
    KEYWORD_HAVING = 295  # reserved keyowrd : SQL-2003-R
    KEYWORD_HELP = 296  # keyword
    KEYWORD_HIGH_PRIORITY = 297  # reserved keyword
    KEYWORD_HISTOGRAM = 298  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_HISTORY = 299  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_HOST = 300  # keyword
    KEYWORD_HOSTS = 301  # keyword
    KEYWORD_HOUR = 302  # keyword : SQL-2003-R
    KEYWORD_HOUR_MICROSECOND = 303  # reserved keyword
    KEYWORD_HOUR_MINUTE = 304  # reserved keyword
    KEYWORD_HOUR_SECOND = 305  # reserved keyword
    KEYWORD_IDENTIFIED = 306  # keyword
    KEYWORD_IF = 307  # reserved keyword
    KEYWORD_IGNORE = 308  # reserved keyword
    KEYWORD_IGNORE_SERVER_IDS = 309  # keyword
    KEYWORD_IMPORT = 310  # keyword
    KEYWORD_IN = 311  # reserved keyword : SQL-2003-R
    KEYWORD_INACTIVE = 312  # keyword (MySQL 8.0)
    KEYWORD_INDEX = 313  # reserved keyword
    KEYWORD_INDEXES = 314  # keyword
    KEYWORD_INFILE = 315  # reserved keyword
    KEYWORD_INITIAL = 316  # keyword : SQL-2016-R (MySQL 8.0)
    KEYWORD_INITIAL_SIZE = 317  # keyword
    KEYWORD_INITIATE = 318  # keyowrd (MySQL 8.0)
    KEYWORD_INNER = 319  # reserved keyword : SQL-2003-R
    KEYWORD_INOUT = 320  # reserved keyword : SQL-2003-R
    KEYWORD_INSENSITIVE = 321  # reserved keyword : SQL-2003-R
    KEYWORD_INSERT = 322  # reserved keyword : SQL-2003-R
    KEYWORD_INSERT_METHOD = 323  # keyword
    KEYWORD_INSTALL = 324  # keyword
    KEYWORD_INSTANCE = 325  # keyword
    KEYWORD_INT = 326  # reserved keyword : SQL-2003-R
    KEYWORD_INT1 = 327  # reserved keyword
    KEYWORD_INT2 = 328  # reserved keyword
    KEYWORD_INT3 = 329  # reserved keyword
    KEYWORD_INT4 = 330  # reserved keyword
    KEYWORD_INT8 = 331  # reserved keyword
    KEYWORD_INTEGER = 332  # reserved keyword
    KEYWORD_INTERSECT = 333  # reserved keyowrd : SQL-1992-R (MySQL 8.0)
    KEYWORD_INTERVAL = 334  # reserved keyword : SQL-2003-R
    KEYWORD_INTO = 335  # reserved keyword : SQL-2003-R
    KEYWORD_INVISIBLE = 336  # keyword
    KEYWORD_INVOKER = 337  # keyword
    KEYWORD_IO = 338  # keyword
    KEYWORD_IO_AFTER_GTIDS = 339  # reserved keyword : MYSQL, FUTURE-USE
    KEYWORD_IO_BEFORE_GTIDS = 340  # reserved keyword : MYSQL, FUTURE-USE
    KEYWORD_IO_THREAD = 341  # reserved keyword
    KEYWORD_IPC = 342  # keyword
    KEYWORD_IS = 343  # reserved keyword : SQL-2003-R
    KEYWORD_ISOLATION = 344  # keyword : SQL-2003-R
    KEYWORD_ISSUER = 345  # keyword
    KEYWORD_ITERATE = 346  # reserved keyword
    KEYWORD_JOIN = 347  # reserved keyword : SQL-2003-R
    KEYWORD_JSON = 348  # keyword : MYSQL
    KEYWORD_JSON_TABLE = 349  # reserved keyword : SQL-2016-R (MySQL 8.0)
    KEYWORD_JSON_VALUE = 350  # keyword : SQL-2016-R (MySQL 8.0)
    KEYWORD_KEY = 351  # reserved keyword : SQL-2003-N
    KEYWORD_KEYRING = 352  # keyword (MySQL 8.0)
    KEYWORD_KEYS = 353  # reserved keyword
    KEYWORD_KEY_BLOCK_SIZE = 354  # keyword
    KEYWORD_KILL = 355  # reserved keyword
    KEYWORD_LAG = 356  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_LANGUAGE = 357  # keyword : SQL-2003-R
    KEYWORD_LAST = 358  # keyword : SQL-2003-N
    KEYWORD_LAST_VALUE = 359  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_LATERAL = 360  # reserved keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_LEAD = 361  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_LEADING = 362  # reserved keyword : SQL-2003-R
    KEYWORD_LEAVE = 363  # reserved keyword
    KEYWORD_LEAVES = 364  # keyword
    KEYWORD_LEFT = 365  # reserved keyword : SQL-2003-R
    KEYWORD_LESS = 366  # keyword
    KEYWORD_LEVEL = 367  # keyword
    KEYWORD_LIKE = 368  # reserved keyword : SQL-2003-R
    KEYWORD_LIMIT = 369  # reserved keyword
    KEYWORD_LINEAR = 370  # reserved keyword
    KEYWORD_LINES = 371  # reserved keyword
    KEYWORD_LINESTRING = 372  # keyword : MYSQL
    KEYWORD_LIST = 373  # keyword
    KEYWORD_LOAD = 374  # reserved keyword
    KEYWORD_LOCAL = 375  # keyword : SQL-2003-R
    KEYWORD_LOCALTIME = 376  # reserved keyword
    KEYWORD_LOCALTIMESTAMP = 377  # reserved keyword
    KEYWORD_LOCK = 378  # reserved keyword
    KEYWORD_LOCKED = 379  # keyword (MySQL 8.0)
    KEYWORD_LOCKS = 380  # keyword
    KEYWORD_LOG = 381  # keyword (MySQL 8.0)
    KEYWORD_LOGFILE = 382  # keyword
    KEYWORD_LOGS = 383  # keyword
    KEYWORD_LONG = 384  # reserved keyword
    KEYWORD_LONGBLOB = 385  # reserved keyword : MYSQL
    KEYWORD_LONGTEXT = 386  # reserved keyword : MYSQL
    KEYWORD_LOOP = 387  # reserved keyword
    KEYWORD_LOW_PRIORITY = 388  # reserved keyword
    KEYWORD_MANUAL = 389  # reserved keyword
    KEYWORD_MASTER = 390  # keyword
    KEYWORD_MASTER_AUTO_POSITION = 391  # keyword
    KEYWORD_MASTER_BIND = 392  # reserved keyword
    KEYWORD_MASTER_COMPRESSION_ALGORITHM = 393  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_MASTER_CONNECT_RETRY = 394  # keyword
    KEYWORD_MASTER_DELAY = 395  # keyword
    KEYWORD_MASTER_HEARTBEAT_PERIOD = 396  # keyword
    KEYWORD_MASTER_HOST = 397  # keyword
    KEYWORD_MASTER_LOG_FILE = 398  # keyword
    KEYWORD_MASTER_LOG_POS = 399  # keyword
    KEYWORD_MASTER_PASSWORD = 400  # keyword
    KEYWORD_MASTER_PORT = 401  # keyword
    KEYWORD_MASTER_PUBLIC_KEY_PATH = 402  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_MASTER_RETRY_COUNT = 403  # keyword
    KEYWORD_MASTER_SSL = 404  # keyword
    KEYWORD_MASTER_SSL_CA = 405  # keyword
    KEYWORD_MASTER_SSL_CAPATH = 406  # keyword
    KEYWORD_MASTER_SSL_CERT = 407  # keyword
    KEYWORD_MASTER_SSL_CIPHER = 408  # keyword
    KEYWORD_MASTER_SSL_CRL = 409  # keyword
    KEYWORD_MASTER_SSL_CRLPATH = 410  # keyword
    KEYWORD_MASTER_SSL_KEY = 411  # keyword
    KEYWORD_MASTER_SSL_VERIFY_SERVER_CERT = 412  # reserved keyword
    KEYWORD_MASTER_TLS_CIPHERSUITES = 413  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_MASTER_TLS_VERSION = 414  # keyword
    KEYWORD_MASTER_USER = 415  # keyword
    KEYWORD_MASTER_ZSTD_COMPRESSION_LEVEL = 416  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_MATCH = 417  # reserved keyword : SQL-2003-R
    KEYWORD_MAX_VALUE = 418  # reserved keyword : SQL-2003-N
    KEYWORD_MAX_CONNECTIONS_PER_HOUR = 419  # keyword
    KEYWORD_MAX_QUERIES_PER_HOUR = 420  # keyword
    KEYWORD_MAX_ROWS = 421  # keyword
    KEYWORD_MAX_SIZE = 422  # keyword
    KEYWORD_MAX_UPDATES_PER_HOUR = 423  # keyword
    KEYWORD_MAX_USER_CONNECTIONS = 424  # keyword
    KEYWORD_MEDIUM = 425  # keyword
    KEYWORD_MEDIUMBLOB = 426  # reserved keyword : MYSQL
    KEYWORD_MEDIUMINT = 427  # reserved keyword : MYSQL
    KEYWORD_MEDIUMTEXT = 428  # reserved keyword : MYSQL
    KEYWORD_MEMBER = 429  # keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_MEMORY = 430  # keyword
    KEYWORD_MERGE = 431  # keyword : SQL-2003-R
    KEYWORD_MESSAGE_TEXT = 432  # keyword : SQL-2003-N
    KEYWORD_MICROSECOND = 433  # keyword : MYSQL-FUNC
    KEYWORD_MIDDLEINT = 434  # reserved keyword
    KEYWORD_MIGRATE = 435  # keyword
    KEYWORD_MINUTE = 436  # keyword : SQL-2003-R
    KEYWORD_MINUTE_MICROSECOND = 437  # reserved keyword
    KEYWORD_MINUTE_SECOND = 438  # reserved keyword
    KEYWORD_MIN_ROWS = 439  # keyword
    KEYWORD_MOD = 440  # reserved keyword : SQL-2003-N
    KEYWORD_MODE = 441  # keyword
    KEYWORD_MODIFIES = 442  # keyword : SQL-2003-R
    KEYWORD_MODIFY = 443  # keyword
    KEYWORD_MONTH = 444  # keyword : SQL-2003-R
    KEYWORD_MULTILINESTRING = 445  # keyword : MYSQL
    KEYWORD_MULTIPOINT = 446  # keyword : MYSQL
    KEYWORD_MULTIPOLYGON = 447  # keyword : MYSQL
    KEYWORD_MUTEX = 448  # keyword
    KEYWORD_MYSQL_ERRNO = 449  # keyword
    KEYWORD_NAME = 450  # keyword : SQL-2003-N
    KEYWORD_NAMES = 451  # keyword : SQL-2003-N
    KEYWORD_NATIONAL = 452  # keyword : SQL-2003-R
    KEYWORD_NATURAL = 453  # reserved keyword : SQL-2003-R
    KEYWORD_NCHAR = 454  # keyword : SQL-2003-R
    KEYWORD_NDB = 455  # reserved keyword
    KEYWORD_NDBCLUSTER = 456  # keyword
    KEYWORD_NESTED = 457  # keyword : SQL-2016-N (MySQL 8.0)
    KEYWORD_NETWORK_NAMESPACE = 458  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_NEVER = 459  # keyword
    KEYWORD_NEW = 460  # keyword : SQL-2003-R
    KEYWORD_NEXT = 461  # keyword : SQL-2003-N
    KEYWORD_NO = 462  # keyword : SQL-2003-R
    KEYWORD_NODEGROUP = 463  # keyword
    KEYWORD_NONE = 464  # keyword : SQL-2003-R
    KEYWORD_NOT = 465  # reserved keyword : SQL-2003-R
    # KEYWORD_NOT2 = 466  # reserved keyword : SQL-2003-R (sql_mode & MODE_HIGH_NOT_PRECEDENCE)
    KEYWORD_NOWAIT = 467  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_NO_WAIT = 468  # keyword
    KEYWORD_NO_WRITE_TO_BINLOG = 469  # reserved keyword
    KEYWORD_NTH_VALUE = 470  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_NTILE = 471  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_NULL = 472  # reserved keyword : SQL-2003-R
    KEYWORD_NULLS = 473  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_NUMBER = 474  # keyword : SQL-2003-N
    KEYWORD_NUMERIC = 475  # reserved keyword : SQL-2003-R
    KEYWORD_NVARCHAR = 476  # keyword
    KEYWORD_OF = 477  # reserved keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_OFF = 478  # keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_OFFSET = 479  # keyword
    KEYWORD_OJ = 480  # keyword : ODBC (MySQL 8.0)
    KEYWORD_OLD = 481  # keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_ON = 482  # reserved keyword : SQL-2003-R
    KEYWORD_ONE = 483  # keyword
    KEYWORD_ONLY = 484  # keyword : SQL-2003-R
    KEYWORD_OPEN = 485  # keyword : SQL-2003-R
    KEYWORD_OPTIMIZE = 486  # reserved keyword
    KEYWORD_OPTIMIZER_COSTS = 487  # reserved keyword
    KEYWORD_OPTION = 488  # reserved keyword : SQL-2003-N
    KEYWORD_OPTIONAL = 489  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_OPTIONALLY = 490  # reserved keyowrd
    KEYWORD_OPTIONS = 491  # keyword
    KEYWORD_OR = 492  # reserved keyowrd : SQL-2003-R
    KEYWORD_OR2 = 493  # reserved keyowrd : SQL-2003-R (sql_mode & MODE_PIPES_AS_CONCAT)
    KEYWORD_ORDER = 494  # reserved keyword : SQL-2003-R
    KEYWORD_ORDINALITY = 495  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_ORGANIZATION = 496  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_OTHERS = 497  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_OUT = 498  # reserved keyword : SQL-2003-R
    KEYWORD_OUTER = 499  # reserved keyowrd
    KEYWORD_OUTFILE = 500  # reserved keyowrd
    KEYWORD_OVER = 501  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_OWNER = 502  # keyword
    KEYWORD_PACK_KEYS = 503  # keyword
    KEYWORD_PAGE = 504  # keyword
    KEYWORD_PARALLEL = 505  # reserved keyword (MySQL 8.0)
    KEYWORD_PARSER = 506  # keyword
    KEYWORD_PARSE_TREE = 507  # keyword (MySQL 8.0)
    KEYWORD_PARTIAL = 508  # keyword : SQL-2003-N
    KEYWORD_PARTITION = 509  # reserved keyword : SQL-2003-R
    KEYWORD_PARTITIONING = 510  # keyword
    KEYWORD_PARTITIONS = 511  # keyword
    KEYWORD_PASSWORD = 512  # keyword
    KEYWORD_PASSWORD_LOCK_TIME = 513  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_PATH = 514  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_PERCENT_RANK = 515  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_PERSIST = 516  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_PERSIST_ONLY = 517  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_PHASE = 518  # keyword
    KEYWORD_PLUGIN = 519  # keyword
    KEYWORD_PLUGINS = 520  # keyword
    KEYWORD_PLUGIN_DIR = 521  # keyword : INTERNAL
    KEYWORD_POINT = 522  # keyword
    KEYWORD_POLYGON = 523  # keyword : MYSQL
    KEYWORD_PORT = 524  # keyword
    KEYWORD_POSITION = 525  # keyword : SQL-2003-N
    KEYWORD_PRECEDES = 526  # keyword : MYSQL
    KEYWORD_PRECEDING = 527  # keyword ； SQL-2003-N (MySQL 8.0)
    KEYWORD_PRECISION = 528  # reserved keyword : SQL-2003-R
    KEYWORD_PREPARE = 529  # keyword : SQL-2003-R
    KEYWORD_PRESERVE = 530  # keyword
    KEYWORD_PREV = 531  # keyword
    KEYWORD_PRIMARY = 532  # reserved keyword : SQL-2003-R
    KEYWORD_PRIVILEGES = 533  # keyword : SQL-2003-N
    KEYWORD_PRIVILEGE_CHECKS_USER = 534  # Keyword : MYSQL (MySQL 8.0)
    KEYWORD_PROCEDURE = 535  # reserved keyword : SQL-2003-R
    KEYWORD_PROCESS = 536  # keyword
    KEYWORD_PROCESSLIST = 537  # keyword
    KEYWORD_PROFILE = 538  # keyword
    KEYWORD_PROFILES = 539  # keyword
    KEYWORD_PROXY = 540  # keyword
    KEYWORD_PURGE = 541  # reserved keyword
    KEYWORD_QUALIFY = 542  # reserved keyword (MySQL 8.0)
    KEYWORD_QUARTER = 543  # keyword
    KEYWORD_QUERY = 544  # keyword
    KEYWORD_QUICK = 545  # keyword
    KEYWORD_RANDOM = 546  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_RANGE = 547  # reserved keyword : SQL-2003-R
    KEYWORD_RANK = 548  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_READ = 549  # reserved keyword : SQL-2003-N
    KEYWORD_READS = 550  # reserved keyword : SQL-2003-R
    KEYWORD_READ_ONLY = 551  # keyword
    KEYWORD_READ_WRITE = 552  # reserved keyword
    KEYWORD_REAL = 553  # reserved keyowrd : SQL-2003-R
    KEYWORD_REBUILD = 554  # keyword
    KEYWORD_RECOVER = 555  # keyword
    KEYWORD_RECURSIVE = 556  # reserved keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_REDO_BUFFER_SIZE = 557  # keyword
    KEYWORD_REDUNDANT = 558  # keyword
    KEYWORD_REFERENCE = 559  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_REFERENCES = 560  # reserved keyword : SQL-2003-R
    KEYWORD_REGEXP = 561  # reserved keyword
    KEYWORD_REGISTRATION = 562  # keyword (MySQL 8.0)
    KEYWORD_RELAY = 563  # keyword
    KEYWORD_RELAYLOG = 564  # keyword
    KEYWORD_RELAY_LOG_FILE = 565  # keyword
    KEYWORD_RELAY_LOG_POS = 566  # keyword
    KEYWORD_RELAY_THREAD = 567  # keyword
    KEYWORD_RELEASE = 568  # reserved keyword : SQL-2003-R
    KEYWORD_RELOAD = 569  # keyowrd
    KEYWORD_REMOVE = 570  # keyowrd
    KEYWORD_ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS = 571  # keyowrd
    KEYWORD_RENAME = 572  # reserved keyword
    KEYWORD_REORGANIZE = 573  # keyword
    KEYWORD_REPAIR = 574  # keyword
    KEYWORD_REPEAT = 575  # reserved keyword : MYSQL-FUNC
    KEYWORD_REPEATABLE = 576  # keyword : SQL-2003-N
    KEYWORD_REPLACE = 577  # reserved keyword : MYSQL-FUNC
    KEYWORD_REPLICA = 578  # keyword
    KEYWORD_REPLICAS = 579  # keyword
    KEYWORD_REPLICATE_DO_DB = 580  # keyword
    KEYWORD_REPLICATE_DO_TABLE = 581  # keyword
    KEYWORD_REPLICATE_IGNORE_DB = 582  # keyword
    KEYWORD_REPLICATE_IGNORE_TABLE = 583  # keyword
    KEYWORD_REPLICATE_REWRITE_DB = 584  # keyword
    KEYWORD_REPLICATE_WILD_DO_TABLE = 585  # keyword
    KEYWORD_REPLICATE_WILD_IGNORE_TABLE = 586  # keyword
    KEYWORD_REPLICATION = 587  # keyword
    KEYWORD_REQUIRE = 588  # reserved keyword
    KEYWORD_REQUIRE_ROW_FORMAT = 589  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_REQUIRE_TABLE_PRIMARY_KEY_CHECK = 590  # keyword
    KEYWORD_RESET = 591  # keyword
    KEYWORD_RESIGNAL = 592  # reserved keyword : SQL-2003-R
    KEYWORD_RESOURCE = 593  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_RESPECT = 594  # keyword : SQL_2011-N (MySQL 8.0)
    KEYWORD_RESTART = 595  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_RESTORE = 596  # keyword
    KEYWORD_RESTRICT = 597  # reserved keyword
    KEYWORD_RESUME = 598  # keyword
    KEYWORD_RETAIN = 599  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_RETURN = 600  # reserved keyword : SQL-2003-R
    KEYWORD_RETURNED_SQLSTATE = 601  # keyword : SQL-2003-N
    KEYWORD_RETURNING = 602  # keyword : SQL-2016-N (MySQL 8.0)
    KEYWORD_RETURNS = 603  # keyword : SQL-2003-R
    KEYWORD_REUSE = 604  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_REVERSE = 605  # keyword
    KEYWORD_REVOKE = 606  # reserved keyword : SQL-2003-R
    KEYWORD_RIGHT = 607  # reserved keyword : SQL-2003-R
    KEYWORD_RLIKE = 608  # reserved keyword
    KEYWORD_ROLE = 609  # keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_ROLLBACK = 610  # keyword : SQL-2003-R
    KEYWORD_ROLLUP = 611  # keyword : SQL-2003-R
    KEYWORD_ROTATE = 612  # keyword
    KEYWORD_ROUTINE = 613  # keyword : SQL-2003-N
    KEYWORD_ROW = 614  # reserved keyword : SQL-2003-R
    KEYWORD_ROWS = 615  # reserved keyword : SQL-2003-R
    KEYWORD_ROW_COUNT = 616  # keyword : SQL-2003-N
    KEYWORD_ROW_FORMAT = 617  # keyword
    KEYWORD_ROW_NUMBER = 618  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_RTREE = 619  # keyword
    KEYWORD_S3 = 620  # keyword (MySQL 8.0)
    KEYWORD_SAVEPOINT = 621  # keyword : SQL-2003-R
    KEYWORD_SCHEDULE = 622  # keyword
    KEYWORD_SCHEMA = 623  # reserved keyword
    KEYWORD_SCHEMAS = 624  # reserved keyword
    KEYWORD_SCHEMA_NAME = 625  # keyword : SQL-2003-N
    KEYWORD_SECOND = 626  # keyword : SQL-2003-R
    KEYWORD_SECONDARY = 627  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SECONDARY_ENGINE = 628  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SECONDARY_ENGINE_ATTRIBUTE = 629  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SECONDARY_LOAD = 630  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SECONDARY_UNLOAD = 631  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SECOND_MICROSECOND = 632  # reserved keyword
    KEYWORD_SECURITY = 633  # keyword : SQL-2003-N
    KEYWORD_SELECT = 634  # reserved keyword : SQL-2003-R
    KEYWORD_SENSITIVE = 635  # reserved keyword : FUTURE-USE
    KEYWORD_SEPARATOR = 636  # reserved keyword
    KEYWORD_SERIAL = 637  # keyword
    KEYWORD_SERIALIZABLE = 638  # keyword : SQL-2003-N
    KEYWORD_SERVER = 639  # keyword
    KEYWORD_SESSION = 640  # keyword : SQL-2003-N
    KEYWORD_SET = 641  # reserved keyword : SQL-2003-R
    KEYWORD_SHARE = 642  # keyword
    KEYWORD_SHOW = 643  # reserved keyword
    KEYWORD_SHUTDOWN = 644  # keyword
    KEYWORD_SIGNAL = 645  # reserved keyword : SQL-2003-R
    KEYWORD_SIGNED = 646  # keyword
    KEYWORD_SIMPLE = 647  # keyword : SQL-2003-N
    KEYWORD_SKIP = 648  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SLAVE = 649  # keyword
    KEYWORD_SLOW = 650  # keyword
    KEYWORD_SMALLINT = 651  # reserved keyword : SQL-2003-R
    KEYWORD_SNAPSHOT = 652  # keyword
    KEYWORD_SOCKET = 653  # keyword
    KEYWORD_SOME = 654  # reserved keyword
    KEYWORD_SONAME = 655  # keyword
    KEYWORD_SOUNDS = 656  # keyword
    KEYWORD_SOURCE = 657  # keyword
    KEYWORD_SOURCE_AUTO_POSITION = 658  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_BIND = 659  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_COMPRESSION_ALGORITHM = 660  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_CONNECTION_AUTO_FAILOVER = 661  # keyword
    KEYWORD_SOURCE_CONNECT_RETRY = 662  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_DELAY = 663  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_HEARTBEAT_PERIOD = 664  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_HOST = 665  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_LOG_FILE = 666  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_LOG_POS = 667  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_PASSWORD = 668  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_PORT = 669  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_PUBLIC_KEY_PATH = 670  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_RETRY_COUNT = 671  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL = 672  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CA = 673  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CAPATH = 674  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CERT = 675  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CIPHER = 676  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CRL = 677  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CRLPATH = 678  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_KEY = 679  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_VERIFY_SERVER_CERT = 680  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_TLS_CIPHERSUITES = 681  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_TLS_VERSION = 682  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_USER = 683  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_ZSTD_COMPRESSION_LEVEL = 684  # keyword (MySQL 8.0)
    KEYWORD_SPATIAL = 685  # reserved keyword
    KEYWORD_SPECIFIC = 686  # reserved keyword : SQL-2003-R
    KEYWORD_SQL = 687  # reserved keyword : SQL-2003-R
    KEYWORD_SQLEXCEPTION = 688  # reserved keyword : SQL-2003-R
    KEYWORD_SQLSTATE = 689  # reserved keyword : SQL-2003-R
    KEYWORD_SQLWARNING = 690  # reserved keyword : SQL-2003-R
    KEYWORD_SQL_AFTER_GTIDS = 691  # keyword : MYSQL
    KEYWORD_SQL_AFTER_MTS_GAPS = 692  # keyword : MYSQL
    KEYWORD_SQL_BEFORE_GTIDS = 693  # keyword : MYSQL
    KEYWORD_SQL_BIG_RESULT = 694  # reserved keyword
    KEYWORD_SQL_BUFFER_RESULT = 695  # keyword
    KEYWORD_SQL_CALC_FOUND_ROWS = 696  # reserved keyword
    KEYWORD_SQL_NO_CACHE = 697  # keyword
    KEYWORD_SQL_SMALL_RESULT = 698  # reserved keyword
    KEYWORD_SQL_THREAD = 699  # keyword
    KEYWORD_SQL_TSI_DAY = 700  # keyword
    KEYWORD_SQL_TSI_HOUR = 701  # keyword
    KEYWORD_SQL_TSI_MINUTE = 702  # keyword
    KEYWORD_SQL_TSI_MONTH = 703  # keyword
    KEYWORD_SQL_TSI_QUARTER = 704  # keyword
    KEYWORD_SQL_TSI_SECOND = 705  # keyword
    KEYWORD_SQL_TSI_WEEK = 706  # keyword
    KEYWORD_SQL_TSI_YEAR = 707  # keyword
    KEYWORD_SRID = 708  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SSL = 709  # reserved keyword
    KEYWORD_ST_COLLECT = 710  # word (MySQL 8.0)
    KEYWORD_STACKED = 711  # keyword : SQL-2003-N
    KEYWORD_START = 712  # keyword : SQL-2003-R
    KEYWORD_STARTING = 713  # reserved keyword
    KEYWORD_STARTS = 714  # keyword
    KEYWORD_STATS_AUTO_RECALC = 715  # keyword
    KEYWORD_STATS_PERSISTENT = 716  # keyword
    KEYWORD_STATS_SAMPLE_PAGES = 717  # keyword
    KEYWORD_STATUS = 718  # keyword
    KEYWORD_STOP = 719  # keyword
    KEYWORD_STORAGE = 720  # keyword
    KEYWORD_STORED = 721  # reserved keyword
    KEYWORD_STRAIGHT_JOIN = 722  # reserved keyword
    KEYWORD_STREAM = 723  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_STRING = 724  # keyword
    KEYWORD_SUBCLASS_ORIGIN = 725  # keyword : SQL-2003-N
    KEYWORD_SUBJECT = 726  # keyword
    KEYWORD_SUBPARTITION = 727  # keyword
    KEYWORD_SUBPARTITIONS = 728  # keyword
    KEYWORD_SUBDATE = 729  # word
    KEYWORD_SUPER = 730  # keyword
    KEYWORD_SUSPEND = 731  # keyword
    KEYWORD_SWAPS = 732  # keyword
    KEYWORD_SWITCHES = 733  # keyword
    KEYWORD_SYSTEM = 734  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_TABLE = 735  # reserved keyword : SQL-2003-R
    KEYWORD_TABLES = 736  # keyword
    KEYWORD_TABLESAMPLE = 737  # reserved keyword
    KEYWORD_TABLESPACE = 738  # keyword
    KEYWORD_TABLE_CHECKSUM = 739  # keyword
    KEYWORD_TABLE_NAME = 740  # keyword : SQL-2003-N
    KEYWORD_TEMPORARY = 741  # keyword : SQL-2003-N
    KEYWORD_TEMPTABLE = 742  # keyword
    KEYWORD_TERMINATED = 743  # reserved keyword
    KEYWORD_TEXT = 744  # keyword
    KEYWORD_THAN = 745  # keyword
    KEYWORD_THEN = 746  # reserved keyword : SQL-2003-R
    KEYWORD_THREAD_PRIORITY = 747  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_TIES = 748  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_TIME = 749  # keyword : SQL-2003-R
    KEYWORD_TIMESTAMP = 750  # keyword : SQL-2003-R
    KEYWORD_TIMESTAMP_ADD = 751  # keyword
    KEYWORD_TIMESTAMP_DIFF = 752  # keyword
    KEYWORD_TINYBLOB = 753  # reserved keyword : MYSQL
    KEYWORD_TINYINT = 754  # reserved keyword : MYSQL
    KEYWORD_TINYTEXT = 755  # reserved keyword : MYSQL
    KEYWORD_TLS = 756  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_TO = 757  # reserved keyword : SQL-2003-R
    KEYWORD_TRAILING = 758  # reserved keyword : SQL-2003-R
    KEYWORD_TRANSACTION = 759  # keyword
    KEYWORD_TRIGGER = 760  # reserved keyword : SQL-2003-R
    KEYWORD_TRIGGERS = 761  # keyword
    KEYWORD_TRUE = 762  # reserved keyword : SQL-2003-R
    KEYWORD_TRUNCATE = 763  # keyword
    KEYWORD_TYPE = 764  # keyword : SQL-2003-N
    KEYWORD_TYPES = 765  # keyword
    KEYWORD_UNBOUNDED = 766  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_UNCOMMITTED = 767  # keyword : SQL-2003-N
    KEYWORD_UNDEFINED = 768  # keyword
    KEYWORD_UNDO = 769  # reserved keyword : FUTURE-USE
    KEYWORD_UNDOFILE = 770  # keyword
    KEYWORD_UNDO_BUFFER_SIZE = 771  # keyword
    KEYWORD_UNICODE = 772  # keyword
    KEYWORD_UNINSTALL = 773  # keyword
    KEYWORD_UNION = 774  # reserved keyword : SQL-2003-R
    KEYWORD_UNIQUE = 775  # reserved keyword
    KEYWORD_UNKNOWN = 776  # keyword : SQL-2003-R
    KEYWORD_UNLOCK = 777  # reserved keyword
    KEYWORD_UNREGISTER = 778  # keyword (MySQL 8.0)
    KEYWORD_UNSIGNED = 779  # reserved keyword : MYSQL
    KEYWORD_UNTIL = 780  # keyword
    KEYWORD_UPDATE = 781  # reserved keyword : SQL-2003-R
    KEYWORD_UPGRADE = 782  # keyword
    KEYWORD_URL = 783  # keyword (MySQL 8.0)
    KEYWORD_USAGE = 784  # reserved keyword : SQL-2003-N
    KEYWORD_USE = 785  # reserved keyword
    KEYWORD_USER = 786  # keyword : SQL-2003-R
    KEYWORD_USER_RESOURCES = 787  # reserved keyword
    KEYWORD_USE_FRM = 788  # keyword
    KEYWORD_USING = 789  # reserved keyword : SQL-2003-R
    KEYWORD_UTC_DATE = 790  # reserved keyword
    KEYWORD_UTC_TIME = 791  # reserved keyword
    KEYWORD_UTC_TIMESTAMP = 792  # reserved keyword
    KEYWORD_VALIDATION = 793  # keyword : MYSQL
    KEYWORD_VALUE = 794  # keyword : SQL-2003-R
    KEYWORD_VALUES = 795  # reserved keyword : SQL-2003-R
    KEYWORD_VARBINARY = 796  # reserved keyword : SQL-2008-R
    KEYWORD_VARCHAR = 797  # reserved keyword : SQL-2003-R
    KEYWORD_VARCHARACTER = 798  # reserved keyword
    KEYWORD_VARIABLES = 799  # keyword
    KEYWORD_VARYING = 800  # reserved keyword : SQL-2003-R
    KEYWORD_VCPU = 801  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_VIEW = 802  # keyword : SQL-2003-N
    KEYWORD_VIRTUAL = 803  # reserved keyword
    KEYWORD_VISIBLE = 804  # keyword
    KEYWORD_WAIT = 805  # keyword
    KEYWORD_WARNINGS = 806  # keyword
    KEYWORD_WEEK = 807  # keyword
    KEYWORD_WEIGHT_STRING = 808  # keyword
    KEYWORD_WHEN = 809  # reserved keyword : SQL-2003-R
    KEYWORD_WHERE = 810  # reserved keyword : SQL-2003-R
    KEYWORD_WHILE = 811  # reserved keyword
    KEYWORD_WINDOW = 812  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_WITH = 813  # reserved keyword : SQL-2003-R
    KEYWORD_WITHOUT = 814  # keyword : SQL-2003-R
    KEYWORD_WORK = 815  # keyword : SQL-2003-N
    KEYWORD_WRAPPER = 816  # keyword
    KEYWORD_WRITE = 817  # reserved keyword : SQL-2003-N
    KEYWORD_X509 = 818  # keyword
    KEYWORD_XA = 819  # keyword
    KEYWORD_XID = 820  # keyword : MYSQL
    KEYWORD_XML = 821  # keyword
    KEYWORD_XOR = 822  # reserved keyword
    KEYWORD_YEAR = 823  # keyword : SQL-2003-R
    KEYWORD_YEAR_MONTH = 824  # reserved keyword
    KEYWORD_ZEROFILL = 825  # reserved keyword : MYSQL
    KEYWORD_ZONE = 826  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_WITH_ROLLUP = 827  # INTERNAL

    # 非关键字函数
    WORD_CURDATE = 828  # MYSQL-FUNC
    WORD_CURTIME = 829  # MYSQL-FUNC
    WORD_DATE_ADD_INTERVAL = 830  # MYSQL-FUNC
    WORD_DATE_SUB_INTERVAL = 831  # MYSQL-FUNC
    WORD_EXTRACT = 832  # SQL-2003-N
    WORD_NOW = 833
    WORD_SYSDATE = 834
    WORD_BIT_AND = 835  # MYSQL-FUNC
    WORD_BIT_OR = 836  # MYSQL-FUNC
    WORD_BIT_XOR = 837  # MYSQL-FUNC
    WORD_COUNT = 838  # SQL-2003-N
    WORD_GROUP_CONCAT = 839
    WORD_JSON_ARRAYAGG = 840  # SQL-2015-R (MySQL 8.0)
    WORD_JSON_OBJECTAGG = 841  # SQL-2015-R (MySQL 8.0)
    WORD_MAX = 842  # SQL-2003-N
    WORD_MIN = 843  # SQL-2003-N
    WORD_STD = 844
    WORD_STDDEV_SAMP = 845  # SQL-2003-N
    WORD_SUM = 846  # SQL-2003-N
    WORD_VAR_SAMP = 847
    WORD_VARIANCE = 848
    WORD_SUBSTRING = 849  # SQL-2003-N
    WORD_TRIM = 850  # SQL-2003-N
    WORD_CAST = 851  # SQL-2003-R
