"""
SQL 终结符
"""

import enum

import metasequoia_parser as ms_parser

__all__ = [
    "SqlTerminalType"
]


@enum.unique
class SqlTerminalType(ms_parser.symbol.TerminalType):
    """终结符类型的枚举类"""

    # 解析器系统符号
    SYSTEM_END_OF_INPUT = 0  # INTERNAL : 词法解析器解析结束
    SYSTEM_ABORT = enum.auto()  # INTERNAL : 词法解析器解析异常

    # 优先级标记符号
    KEYWORD_USED_AS_IDENT = enum.auto()
    KEYWORD_USED_AS_KEYWORD = enum.auto()
    CONDITIONLESS_JOIN = enum.auto()
    STRAIGHT_JOIN = enum.auto()
    NEG = enum.auto()
    SUBQUERY_AS_EXPR = enum.auto()
    EMPTY_FROM_CLAUSE = enum.auto()

    # 单字节运算符
    OPERATOR_PLUS = enum.auto()  # OPERATOR : +
    OPERATOR_CARET = enum.auto()  # OPERATOR : ^
    OPERATOR_TILDE = enum.auto()  # OPERATOR : ~
    OPERATOR_PERCENT = enum.auto()  # OPERATOR : %
    OPERATOR_SUB = enum.auto()  # OPERATOR : -
    OPERATOR_LT = enum.auto()  # OPERATOR : <
    OPERATOR_GT = enum.auto()  # OPERATOR : >
    OPERATOR_EQ = enum.auto()  # OPERATOR : =
    OPERATOR_STAR = enum.auto()  # OPERATOR : *
    OPERATOR_SLASH = enum.auto()  # OPERATOR : /
    OPERATOR_BANG = enum.auto()  # OPERATOR : !
    OPERATOR_AMP = enum.auto()  # OPERATOR : &
    OPERATOR_BAR = enum.auto()  # OPERATOR : |
    OPERATOR_COLON = enum.auto()  # OPERATOR : :
    OPERATOR_LPAREN = enum.auto()  # OPERATOR : (
    OPERATOR_RPAREN = enum.auto()  # OPERATOR : )
    OPERATOR_COMMA = enum.auto()  # OPERATOR : ,
    OPERATOR_LBRACE = enum.auto()  # OPERATOR : {
    OPERATOR_RBRACE = enum.auto()  # OPERATOR : }
    OPERATOR_DOT = enum.auto()  # OPERATOR : .
    OPERATOR_AT = enum.auto()  # OPERATOR : @
    OPERATOR_SEMICOLON = enum.auto()  # OPERATOR : ;
    OPERATOR_DOLLAR = enum.auto()  # OPERATOR : $

    # 多字节运算符
    OPERATOR_AMP_AMP = enum.auto()  # OPERATOR : &&
    OPERATOR_LT_EQ_GT = enum.auto()  # OPERATOR : <=>
    OPERATOR_GT_EQ = enum.auto()  # OPERATOR : >=
    OPERATOR_LT_EQ = enum.auto()  # OPERATOR : <=
    OPERATOR_BANG_EQ = enum.auto()  # OPERATOR : <> 或 !=
    OPERATOR_BAR_BAR = enum.auto()  # OPERATOR : ||
    OPERATOR_LT_LT = enum.auto()  # OPERATOR : <<
    OPERATOR_GT_GT = enum.auto()  # OPERATOR : >>
    OPERATOR_SUB_GT = enum.auto()  # OPERATOR: ->
    OPERATOR_SUB_GT_GT = enum.auto()  # OPERATOR: ->>
    OPERATOR_COLON_EQ = enum.auto()  # OPERATOR: :=

    # 字面值
    LITERAL_BIN_NUM = enum.auto()  # 二进制字面值（仅包含二进制数部分）
    LITERAL_HEX_NUM = enum.auto()  # 十六进制字面值（仅包含十六进制数部分）
    LITERAL_DECIMAL_NUM = enum.auto()  # 不包含 e 或 E 的小数字面值
    LITERAL_FLOAT_NUM = enum.auto()  # 包含 e 或 E 的浮点数字面值
    LITERAL_INT_NUM = enum.auto()  # 整数字面值（在 Python 中不再区分 3 种整型）
    LITERAL_NCHAR_STRING = enum.auto()  # unicode 字符串字面值
    LITERAL_TEXT_STRING = enum.auto()  # 字符串字面值
    LITERAL_UNDERSCORE_CHARSET = enum.auto()  # 下划线开头的字符集名称

    # 标识符
    IDENT = enum.auto()  # 标识符
    IDENT_QUOTED = enum.auto()  # 包含括号的标识符

    # 特殊元素
    LEX_HOSTNAME = enum.auto()  # @ 之后的 Token
    PARAM_MARKER = enum.auto()  # ? 开头的参数值

    # 关键字
    KEYWORD_ACCESSIBLE = enum.auto()  # reserved keyword
    KEYWORD_ACCOUNT = enum.auto()  # keyword
    KEYWORD_ACTION = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_ACTIVE = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_ADD = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_ADDDATE = enum.auto()  # word : MYSQL-FUNC
    KEYWORD_ADMIN = enum.auto()  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_AFTER = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_AGAINST = enum.auto()  # keyword
    KEYWORD_AGGREGATE = enum.auto()  # keyword
    KEYWORD_ALGORITHM = enum.auto()  # keyword
    KEYWORD_ALL = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_ALTER = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_ALWAYS = enum.auto()  # keyword
    KEYWORD_ANALYZE = enum.auto()  # keyword
    KEYWORD_AND = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_ANY = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_ARRAY = enum.auto()  # keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_AS = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_ASC = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_ASCII = enum.auto()  # keyword : MYSQL-FUNC
    KEYWORD_ASENSITIVE = enum.auto()  # reserved keyword : FUTURE-USE
    KEYWORD_AT = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_ATTRIBUTE = enum.auto()  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_AUTHENTICATION = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_AUTO_INC = enum.auto()  # keyword
    KEYWORD_AUTOEXTEND_SIZE = enum.auto()  # keyword
    KEYWORD_AUTO_INCREMENT = enum.auto()  # keyword
    KEYWORD_AVG = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_AVG_ROW_LENGTH = enum.auto()  # keyword
    KEYWORD_BACKUP = enum.auto()  # keyword
    KEYWORD_BEFORE = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_BEGIN = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_BERNOULLI = enum.auto()  # keyword
    KEYWORD_BETWEEN = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_BIGINT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_BINARY = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_BINLOG = enum.auto()  # keyword
    KEYWORD_BIT = enum.auto()  # keyword : MYSQL-FUNC
    KEYWORD_BLOB = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_BLOCK = enum.auto()  # keyword
    KEYWORD_BOOL = enum.auto()  # keyword
    KEYWORD_BOOLEAN = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_BOTH = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_BTREE = enum.auto()  # keyword
    KEYWORD_BUCKETS = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_BULK = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_BY = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_BYTE = enum.auto()  # keyword
    KEYWORD_CACHE = enum.auto()  # keyword
    KEYWORD_CALL = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_CASCADE = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_CASCADED = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_CASE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_CATALOG_NAME = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_CHAIN = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_CHALLENGE_RESPONSE = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_CHANGE = enum.auto()  # reserved keyword
    KEYWORD_CHANGED = enum.auto()  # keyword
    KEYWORD_CHANNEL = enum.auto()  # keyword
    KEYWORD_CHAR = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_CHARACTER = enum.auto()  # reserved keyword
    KEYWORD_CHARSET = enum.auto()  # keyword
    KEYWORD_CHECK = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_CHECKSUM = enum.auto()  # keyword
    KEYWORD_CIPHER = enum.auto()  # keyword
    KEYWORD_CLASS_ORIGIN = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_CLIENT = enum.auto()  # keyword
    KEYWORD_CLONE = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_CLOSE = enum.auto()  # keywrod : SQL-2003-R
    KEYWORD_COALESCE = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_CODE = enum.auto()  # keyword
    KEYWORD_COLLATE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_COLLATION = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_COLUMN = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_COLUMNS = enum.auto()  # keyword
    KEYWORD_COLUMN_FORMAT = enum.auto()  # keyword
    KEYWORD_COLUMN_NAME = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_COMMENT = enum.auto()  # keyword
    KEYWORD_COMMIT = enum.auto()  # keyowrd : SQL-2003-R
    KEYWORD_COMMITTED = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_COMPACT = enum.auto()  # keyword
    KEYWORD_COMPLETION = enum.auto()  # keyword
    KEYWORD_COMPONENT = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_COMPRESSED = enum.auto()  # keyword
    KEYWORD_COMPRESSION = enum.auto()  # keyword
    KEYWORD_CONCURRENT = enum.auto()  # keyword
    KEYWORD_CONDITION = enum.auto()  # reserved keyword : SQL-2003-R, SQL-2008-R
    KEYWORD_CONNECTION = enum.auto()  # keyword
    KEYWORD_CONSISTENT = enum.auto()  # keyword
    KEYWORD_CONSTRAINT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_CONSTRAINT_CATALOG = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_CONSTRAINT_NAME = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_CONSTRAINT_SCHEMA = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_CONTAINS = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_CONTEXT = enum.auto()  # keyword
    KEYWORD_CONTINUE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_CONVERT = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_CPU = enum.auto()  # keyword
    KEYWORD_CREATE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_CROSS = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_CUBE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_CUME_DIST = enum.auto()  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_CURRENT = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_CURRENT_DATE = enum.auto()  # reserved keyword
    KEYWORD_CURRENT_TIME = enum.auto()  # reserved keyword
    KEYWORD_CURRENT_TIMESTAMP = enum.auto()  # reserved keyword
    KEYWORD_CURRENT_USER = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_CURSOR = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_CURSOR_NAME = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_DATA = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_DATABASE = enum.auto()  # reserved keyword
    KEYWORD_DATABASES = enum.auto()  # reserved keyword
    KEYWORD_DATAFILE = enum.auto()  # keyword
    KEYWORD_DATE = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_DATETIME = enum.auto()  # keyword
    KEYWORD_DAY = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_DAY_HOUR = enum.auto()  # reserved keyword
    KEYWORD_DAY_MICROSECOND = enum.auto()  # reserved keyword
    KEYWORD_DAY_MINUTE = enum.auto()  # reserved keyword
    KEYWORD_DAY_SECOND = enum.auto()  # reserved keyword
    KEYWORD_DEALLOCATE = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_DEC = enum.auto()  # reserved keyword
    KEYWORD_DECIMAL = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_DECLARE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_DEFAULT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_DEFAULT_AUTH = enum.auto()  # keyword : INTERNAL
    KEYWORD_DEFINER = enum.auto()  # keyword
    KEYWORD_DEFINITION = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_DELAYED = enum.auto()  # reserved keyword
    KEYWORD_DELAY_KEY_WRITE = enum.auto()  # keyword
    KEYWORD_DELETE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_DENSE_RANK = enum.auto()  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_DESC = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_DESCRIBE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_DESCRIPTION = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_DETERMINISTIC = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_DIAGNOSTICS = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_DIRECTORY = enum.auto()  # keyword
    KEYWORD_DISABLE = enum.auto()  # keyword
    KEYWORD_DISCARD = enum.auto()  # keyword : MYSQL
    KEYWORD_DISK = enum.auto()  # keyword
    KEYWORD_DISTINCT = enum.auto()  # reserved keyowrd : SQL-2003-R
    KEYWORD_DISTINCTROW = enum.auto()  # reserved keyowrd
    KEYWORD_DIV = enum.auto()  # reserved keyword
    KEYWORD_DO = enum.auto()  # keyword
    KEYWORD_DOUBLE = enum.auto()  # reserved keyowrd : SQL-2003-R
    KEYWORD_DROP = enum.auto()  # reserved keyowrd : SQL-2003-R
    KEYWORD_DUAL = enum.auto()  # reserved keyword
    KEYWORD_DUMPFILE = enum.auto()  # keyword
    KEYWORD_DUPLICATE = enum.auto()  # keyword
    KEYWORD_DYNAMIC = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_EACH = enum.auto()  # reserved keyword: SQL-2003-R
    KEYWORD_ELSE = enum.auto()  # reserved keyword: SQL-2003-R
    KEYWORD_ELSEIF = enum.auto()  # reserved keyword
    KEYWORD_EMPTY = enum.auto()  # reserved keyword: SQL-2016-R (MySQL 8.0)
    KEYWORD_ENABLE = enum.auto()  # keyword
    KEYWORD_ENCLOSED = enum.auto()  # reserved keyword
    KEYWORD_ENCRYPTION = enum.auto()  # keyword
    KEYWORD_END = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_ENDS = enum.auto()  # keyword
    KEYWORD_ENFORCED = enum.auto()  # keyword : SQL-2015-N (MySQL 8.0)
    KEYWORD_ENGINE = enum.auto()  # keyword
    KEYWORD_ENGINES = enum.auto()  # keyword
    KEYWORD_ENGINE_ATTRIBUTE = enum.auto()  # Keyword : MYSQL (MySQL 8.0)
    KEYWORD_ENUM = enum.auto()  # keyword : MYSQL
    KEYWORD_ERROR = enum.auto()  # keyword
    KEYWORD_ERRORS = enum.auto()  # keyword
    KEYWORD_ESCAPE = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_ESCAPED = enum.auto()  # reserved keyword
    KEYWORD_EVENT = enum.auto()  # keyword
    KEYWORD_EVENTS = enum.auto()  # keyword
    KEYWORD_EVERY = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_EXCEPT = enum.auto()  # reserved keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_EXCHANGE = enum.auto()  # keyword
    KEYWORD_EXCLUDE = enum.auto()  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_EXECUTE = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_EXISTS = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_EXIT = enum.auto()  # reserved keyword
    KEYWORD_EXPANSION = enum.auto()  # keyword
    KEYWORD_EXPIRE = enum.auto()  # keyword
    KEYWORD_EXPLAIN = enum.auto()  # reserved keyword
    KEYWORD_EXPORT = enum.auto()  # keyword
    KEYWORD_EXTENDED = enum.auto()  # keyword
    KEYWORD_EXTENT_SIZE = enum.auto()  # keyword
    KEYWORD_FACTOR = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_FAILED_LOGIN_ATTEMPTS = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_FALSE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_FAST = enum.auto()  # keyword
    KEYWORD_FAULTS = enum.auto()  # keyword
    KEYWORD_FETCH = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_FIELDS = enum.auto()  # keyword
    KEYWORD_FILE = enum.auto()  # keyword
    KEYWORD_FILE_BLOCK_SIZE = enum.auto()  # keyword
    KEYWORD_FILTER = enum.auto()  # keyword
    KEYWORD_FINISH = enum.auto()  # keyword : SQL-2016-N (MySQL 8.0)
    KEYWORD_FIRST = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_FIRST_VALUE = enum.auto()  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_FIXED = enum.auto()  # keyword
    KEYWORD_FLOAT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_FLOAT4 = enum.auto()  # reserved keyword
    KEYWORD_FLOAT8 = enum.auto()  # reserved keyword
    KEYWORD_FLUSH = enum.auto()  # keyword
    KEYWORD_FOLLOWING = enum.auto()  # keyowrd : SQL-2003-N (MySQL 8.0)
    KEYWORD_FOLLOWS = enum.auto()  # keyword : MYSQL
    KEYWORD_FOR = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_FORCE = enum.auto()  # reserved keyword
    KEYWORD_FOREIGN = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_FORMAT = enum.auto()  # keyword
    KEYWORD_FOUND = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_FROM = enum.auto()  # reserved keyword
    KEYWORD_FULL = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_FULLTEXT = enum.auto()  # reserved keyword
    KEYWORD_FUNCTION = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_GENERAL = enum.auto()  # keyword
    KEYWORD_GENERATE = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_GENERATED = enum.auto()  # keyword
    KEYWORD_GEOMCOLLECTION = enum.auto()  # reserved keyword
    KEYWORD_GEOMETRY = enum.auto()  # keyword
    KEYWORD_GEOMETRYCOLLECTION = enum.auto()  # keyword : MYSQL
    KEYWORD_GET = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_GET_MASTER_PUBLIC_KEY = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_GET_FORMAT = enum.auto()  # keyword : MYSQL-FUNC
    KEYWORD_GET_SOURCE_PUBLIC_KEY = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_GLOBAL = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_GRANT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_GRANTS = enum.auto()  # keyword
    KEYWORD_GROUP = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_GROUPING = enum.auto()  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_GROUPS = enum.auto()  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_GROUP_REPLICATION = enum.auto()  # keyword
    KEYWORD_GTIDS = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_GTID_ONLY = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_HANDLER = enum.auto()  # keyword
    KEYWORD_HASH = enum.auto()  # keyword
    KEYWORD_HAVING = enum.auto()  # reserved keyowrd : SQL-2003-R
    KEYWORD_HELP = enum.auto()  # keyword
    KEYWORD_HIGH_PRIORITY = enum.auto()  # reserved keyword
    KEYWORD_HISTOGRAM = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_HISTORY = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_HOST = enum.auto()  # keyword
    KEYWORD_HOSTS = enum.auto()  # keyword
    KEYWORD_HOUR = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_HOUR_MICROSECOND = enum.auto()  # reserved keyword
    KEYWORD_HOUR_MINUTE = enum.auto()  # reserved keyword
    KEYWORD_HOUR_SECOND = enum.auto()  # reserved keyword
    KEYWORD_IDENTIFIED = enum.auto()  # keyword
    KEYWORD_IF = enum.auto()  # reserved keyword
    KEYWORD_IGNORE = enum.auto()  # reserved keyword
    KEYWORD_IGNORE_SERVER_IDS = enum.auto()  # keyword
    KEYWORD_IMPORT = enum.auto()  # keyword
    KEYWORD_IN = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_INACTIVE = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_INDEX = enum.auto()  # reserved keyword
    KEYWORD_INDEXES = enum.auto()  # keyword
    KEYWORD_INFILE = enum.auto()  # reserved keyword
    KEYWORD_INITIAL = enum.auto()  # keyword : SQL-2016-R (MySQL 8.0)
    KEYWORD_INITIAL_SIZE = enum.auto()  # keyword
    KEYWORD_INITIATE = enum.auto()  # keyowrd (MySQL 8.0)
    KEYWORD_INNER = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_INOUT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_INSENSITIVE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_INSERT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_INSERT_METHOD = enum.auto()  # keyword
    KEYWORD_INSTALL = enum.auto()  # keyword
    KEYWORD_INSTANCE = enum.auto()  # keyword
    KEYWORD_INT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_INT1 = enum.auto()  # reserved keyword
    KEYWORD_INT2 = enum.auto()  # reserved keyword
    KEYWORD_INT3 = enum.auto()  # reserved keyword
    KEYWORD_INT4 = enum.auto()  # reserved keyword
    KEYWORD_INT8 = enum.auto()  # reserved keyword
    KEYWORD_INTEGER = enum.auto()  # reserved keyword
    KEYWORD_INTERSECT = enum.auto()  # reserved keyowrd : SQL-1992-R (MySQL 8.0)
    KEYWORD_INTERVAL = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_INTO = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_INVISIBLE = enum.auto()  # keyword
    KEYWORD_INVOKER = enum.auto()  # keyword
    KEYWORD_IO = enum.auto()  # keyword
    KEYWORD_IO_AFTER_GTIDS = enum.auto()  # reserved keyword : MYSQL, FUTURE-USE
    KEYWORD_IO_BEFORE_GTIDS = enum.auto()  # reserved keyword : MYSQL, FUTURE-USE
    KEYWORD_IO_THREAD = enum.auto()  # reserved keyword
    KEYWORD_IPC = enum.auto()  # keyword
    KEYWORD_IS = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_ISOLATION = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_ISSUER = enum.auto()  # keyword
    KEYWORD_ITERATE = enum.auto()  # reserved keyword
    KEYWORD_JOIN = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_JSON = enum.auto()  # keyword : MYSQL
    KEYWORD_JSON_SEPARATOR = enum.auto()  # keyword : MYSQL
    KEYWORD_JSON_UNQUOTED_SEPARATOR = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_JSON_TABLE = enum.auto()  # reserved keyword : SQL-2016-R (MySQL 8.0)
    KEYWORD_JSON_VALUE = enum.auto()  # keyword : SQL-2016-R (MySQL 8.0)
    KEYWORD_KEY = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_KEYRING = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_KEYS = enum.auto()  # reserved keyword
    KEYWORD_KEY_BLOCK_SIZE = enum.auto()  # keyword
    KEYWORD_KILL = enum.auto()  # reserved keyword
    KEYWORD_LAG = enum.auto()  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_LANGUAGE = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_LAST = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_LAST_VALUE = enum.auto()  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_LATERAL = enum.auto()  # reserved keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_LEAD = enum.auto()  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_LEADING = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_LEAVE = enum.auto()  # reserved keyword
    KEYWORD_LEAVES = enum.auto()  # keyword
    KEYWORD_LEFT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_LESS = enum.auto()  # keyword
    KEYWORD_LEVEL = enum.auto()  # keyword
    KEYWORD_LIKE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_LIMIT = enum.auto()  # reserved keyword
    KEYWORD_LINEAR = enum.auto()  # reserved keyword
    KEYWORD_LINES = enum.auto()  # reserved keyword
    KEYWORD_LINESTRING = enum.auto()  # keyword : MYSQL
    KEYWORD_LIST = enum.auto()  # keyword
    KEYWORD_LOAD = enum.auto()  # reserved keyword
    KEYWORD_LOCAL = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_LOCALTIME = enum.auto()  # reserved keyword
    KEYWORD_LOCALTIMESTAMP = enum.auto()  # reserved keyword
    KEYWORD_LOCK = enum.auto()  # reserved keyword
    KEYWORD_LOCKED = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_LOCKS = enum.auto()  # keyword
    KEYWORD_LOG = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_LOGFILE = enum.auto()  # keyword
    KEYWORD_LOGS = enum.auto()  # keyword
    KEYWORD_LONG = enum.auto()  # reserved keyword
    KEYWORD_LONGBLOB = enum.auto()  # reserved keyword : MYSQL
    KEYWORD_LONGTEXT = enum.auto()  # reserved keyword : MYSQL
    KEYWORD_LOOP = enum.auto()  # reserved keyword
    KEYWORD_LOW_PRIORITY = enum.auto()  # reserved keyword
    KEYWORD_MANUAL = enum.auto()  # reserved keyword
    KEYWORD_MASTER = enum.auto()  # keyword
    KEYWORD_MASTER_AUTO_POSITION = enum.auto()  # keyword
    KEYWORD_MASTER_BIND = enum.auto()  # reserved keyword
    KEYWORD_MASTER_COMPRESSION_ALGORITHM = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_MASTER_CONNECT_RETRY = enum.auto()  # keyword
    KEYWORD_MASTER_DELAY = enum.auto()  # keyword
    KEYWORD_MASTER_HEARTBEAT_PERIOD = enum.auto()  # keyword
    KEYWORD_MASTER_HOST = enum.auto()  # keyword
    KEYWORD_MASTER_LOG_FILE = enum.auto()  # keyword
    KEYWORD_MASTER_LOG_POS = enum.auto()  # keyword
    KEYWORD_MASTER_PASSWORD = enum.auto()  # keyword
    KEYWORD_MASTER_PORT = enum.auto()  # keyword
    KEYWORD_MASTER_PUBLIC_KEY_PATH = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_MASTER_RETRY_COUNT = enum.auto()  # keyword
    KEYWORD_MASTER_SSL = enum.auto()  # keyword
    KEYWORD_MASTER_SSL_CA = enum.auto()  # keyword
    KEYWORD_MASTER_SSL_CAPATH = enum.auto()  # keyword
    KEYWORD_MASTER_SSL_CERT = enum.auto()  # keyword
    KEYWORD_MASTER_SSL_CIPHER = enum.auto()  # keyword
    KEYWORD_MASTER_SSL_CRL = enum.auto()  # keyword
    KEYWORD_MASTER_SSL_CRLPATH = enum.auto()  # keyword
    KEYWORD_MASTER_SSL_KEY = enum.auto()  # keyword
    KEYWORD_MASTER_SSL_VERIFY_SERVER_CERT = enum.auto()  # reserved keyword
    KEYWORD_MASTER_TLS_CIPHERSUITES = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_MASTER_TLS_VERSION = enum.auto()  # keyword
    KEYWORD_MASTER_USER = enum.auto()  # keyword
    KEYWORD_MASTER_ZSTD_COMPRESSION_LEVEL = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_MATCH = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_MAX_VALUE = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_MAX_CONNECTIONS_PER_HOUR = enum.auto()  # keyword
    KEYWORD_MAX_QUERIES_PER_HOUR = enum.auto()  # keyword
    KEYWORD_MAX_ROWS = enum.auto()  # keyword
    KEYWORD_MAX_SIZE = enum.auto()  # keyword
    KEYWORD_MAX_UPDATES_PER_HOUR = enum.auto()  # keyword
    KEYWORD_MAX_USER_CONNECTIONS = enum.auto()  # keyword
    KEYWORD_MEDIUM = enum.auto()  # keyword
    KEYWORD_MEDIUMBLOB = enum.auto()  # reserved keyword : MYSQL
    KEYWORD_MEDIUMINT = enum.auto()  # reserved keyword : MYSQL
    KEYWORD_MEDIUMTEXT = enum.auto()  # reserved keyword : MYSQL
    KEYWORD_MEMBER = enum.auto()  # keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_MEMORY = enum.auto()  # keyword
    KEYWORD_MERGE = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_MESSAGE_TEXT = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_MICROSECOND = enum.auto()  # keyword : MYSQL-FUNC
    KEYWORD_MIDDLEINT = enum.auto()  # reserved keyword
    KEYWORD_MIGRATE = enum.auto()  # keyword
    KEYWORD_MINUTE = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_MINUTE_MICROSECOND = enum.auto()  # reserved keyword
    KEYWORD_MINUTE_SECOND = enum.auto()  # reserved keyword
    KEYWORD_MIN_ROWS = enum.auto()  # keyword
    KEYWORD_MOD = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_MODE = enum.auto()  # keyword
    KEYWORD_MODIFIES = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_MODIFY = enum.auto()  # keyword
    KEYWORD_MONTH = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_MULTILINESTRING = enum.auto()  # keyword : MYSQL
    KEYWORD_MULTIPOINT = enum.auto()  # keyword : MYSQL
    KEYWORD_MULTIPOLYGON = enum.auto()  # keyword : MYSQL
    KEYWORD_MUTEX = enum.auto()  # keyword
    KEYWORD_MYSQL_ERRNO = enum.auto()  # keyword
    KEYWORD_NAME = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_NAMES = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_NATIONAL = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_NATURAL = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_NCHAR = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_NDB = enum.auto()  # reserved keyword
    KEYWORD_NDBCLUSTER = enum.auto()  # keyword
    KEYWORD_NESTED = enum.auto()  # keyword : SQL-2016-N (MySQL 8.0)
    KEYWORD_NETWORK_NAMESPACE = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_NEVER = enum.auto()  # keyword
    KEYWORD_NEW = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_NEXT = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_NO = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_NODEGROUP = enum.auto()  # keyword
    KEYWORD_NONE = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_NOT = enum.auto()  # reserved keyword : SQL-2003-R
    # KEYWORD_NOT2 = enum.auto()  # reserved keyword : SQL-2003-R (sql_mode & MODE_HIGH_NOT_PRECEDENCE)
    KEYWORD_NOWAIT = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_NO_WAIT = enum.auto()  # keyword
    KEYWORD_NO_WRITE_TO_BINLOG = enum.auto()  # reserved keyword
    KEYWORD_NTH_VALUE = enum.auto()  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_NTILE = enum.auto()  # reserved keyword : SQL-2011-R (MySQL 8.0)
    KEYWORD_NULL = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_NULLS = enum.auto()  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_NUMBER = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_NUMERIC = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_NVARCHAR = enum.auto()  # keyword
    KEYWORD_OF = enum.auto()  # reserved keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_OFF = enum.auto()  # keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_OFFSET = enum.auto()  # keyword
    KEYWORD_OJ = enum.auto()  # keyword : ODBC (MySQL 8.0)
    KEYWORD_OLD = enum.auto()  # keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_ON = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_ONE = enum.auto()  # keyword
    KEYWORD_ONLY = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_OPEN = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_OPTIMIZE = enum.auto()  # reserved keyword
    KEYWORD_OPTIMIZER_COSTS = enum.auto()  # reserved keyword
    KEYWORD_OPTION = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_OPTIONAL = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_OPTIONALLY = enum.auto()  # reserved keyowrd
    KEYWORD_OPTIONS = enum.auto()  # keyword
    KEYWORD_OR = enum.auto()  # reserved keyowrd : SQL-2003-R
    KEYWORD_OR2 = enum.auto()  # reserved keyowrd : SQL-2003-R (sql_mode & MODE_PIPES_AS_CONCAT)
    KEYWORD_ORDER = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_ORDINALITY = enum.auto()  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_ORGANIZATION = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_OTHERS = enum.auto()  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_OUT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_OUTER = enum.auto()  # reserved keyowrd
    KEYWORD_OUTFILE = enum.auto()  # reserved keyowrd
    KEYWORD_OVER = enum.auto()  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_OWNER = enum.auto()  # keyword
    KEYWORD_PACK_KEYS = enum.auto()  # keyword
    KEYWORD_PAGE = enum.auto()  # keyword
    KEYWORD_PARALLEL = enum.auto()  # reserved keyword (MySQL 8.0)
    KEYWORD_PARSER = enum.auto()  # keyword
    KEYWORD_PARSE_TREE = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_PARTIAL = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_PARTITION = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_PARTITIONING = enum.auto()  # keyword
    KEYWORD_PARTITIONS = enum.auto()  # keyword
    KEYWORD_PASSWORD = enum.auto()  # keyword
    KEYWORD_PASSWORD_LOCK_TIME = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_PATH = enum.auto()  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_PERCENT_RANK = enum.auto()  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_PERSIST = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_PERSIST_ONLY = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_PHASE = enum.auto()  # keyword
    KEYWORD_PLUGIN = enum.auto()  # keyword
    KEYWORD_PLUGINS = enum.auto()  # keyword
    KEYWORD_PLUGIN_DIR = enum.auto()  # keyword : INTERNAL
    KEYWORD_POINT = enum.auto()  # keyword
    KEYWORD_POLYGON = enum.auto()  # keyword : MYSQL
    KEYWORD_PORT = enum.auto()  # keyword
    KEYWORD_POSITION = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_PRECEDES = enum.auto()  # keyword : MYSQL
    KEYWORD_PRECEDING = enum.auto()  # keyword ； SQL-2003-N (MySQL 8.0)
    KEYWORD_PRECISION = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_PREPARE = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_PRESERVE = enum.auto()  # keyword
    KEYWORD_PREV = enum.auto()  # keyword
    KEYWORD_PRIMARY = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_PRIVILEGES = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_PRIVILEGE_CHECKS_USER = enum.auto()  # Keyword : MYSQL (MySQL 8.0)
    KEYWORD_PROCEDURE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_PROCESS = enum.auto()  # keyword
    KEYWORD_PROCESSLIST = enum.auto()  # keyword
    KEYWORD_PROFILE = enum.auto()  # keyword
    KEYWORD_PROFILES = enum.auto()  # keyword
    KEYWORD_PROXY = enum.auto()  # keyword
    KEYWORD_PURGE = enum.auto()  # reserved keyword
    KEYWORD_QUALIFY = enum.auto()  # reserved keyword (MySQL 8.0)
    KEYWORD_QUARTER = enum.auto()  # keyword
    KEYWORD_QUERY = enum.auto()  # keyword
    KEYWORD_QUICK = enum.auto()  # keyword
    KEYWORD_RANDOM = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_RANGE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_RANK = enum.auto()  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_READ = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_READS = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_READ_ONLY = enum.auto()  # keyword
    KEYWORD_READ_WRITE = enum.auto()  # reserved keyword
    KEYWORD_REAL = enum.auto()  # reserved keyowrd : SQL-2003-R
    KEYWORD_REBUILD = enum.auto()  # keyword
    KEYWORD_RECOVER = enum.auto()  # keyword
    KEYWORD_RECURSIVE = enum.auto()  # reserved keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_REDO_BUFFER_SIZE = enum.auto()  # keyword
    KEYWORD_REDUNDANT = enum.auto()  # keyword
    KEYWORD_REFERENCE = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_REFERENCES = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_REGEXP = enum.auto()  # reserved keyword
    KEYWORD_REGISTRATION = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_RELAY = enum.auto()  # keyword
    KEYWORD_RELAYLOG = enum.auto()  # keyword
    KEYWORD_RELAY_LOG_FILE = enum.auto()  # keyword
    KEYWORD_RELAY_LOG_POS = enum.auto()  # keyword
    KEYWORD_RELAY_THREAD = enum.auto()  # keyword
    KEYWORD_RELEASE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_RELOAD = enum.auto()  # keyowrd
    KEYWORD_REMOVE = enum.auto()  # keyowrd
    KEYWORD_RENAME = enum.auto()  # reserved keyword
    KEYWORD_REORGANIZE = enum.auto()  # keyword
    KEYWORD_REPAIR = enum.auto()  # keyword
    KEYWORD_REPEAT = enum.auto()  # reserved keyword : MYSQL-FUNC
    KEYWORD_REPEATABLE = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_REPLACE = enum.auto()  # reserved keyword : MYSQL-FUNC
    KEYWORD_REPLICA = enum.auto()  # keyword
    KEYWORD_REPLICAS = enum.auto()  # keyword
    KEYWORD_REPLICATE_DO_DB = enum.auto()  # keyword
    KEYWORD_REPLICATE_DO_TABLE = enum.auto()  # keyword
    KEYWORD_REPLICATE_IGNORE_DB = enum.auto()  # keyword
    KEYWORD_REPLICATE_IGNORE_TABLE = enum.auto()  # keyword
    KEYWORD_REPLICATE_REWRITE_DB = enum.auto()  # keyword
    KEYWORD_REPLICATE_WILD_DO_TABLE = enum.auto()  # keyword
    KEYWORD_REPLICATE_WILD_IGNORE_TABLE = enum.auto()  # keyword
    KEYWORD_REPLICATION = enum.auto()  # keyword
    KEYWORD_REQUIRE = enum.auto()  # reserved keyword
    KEYWORD_REQUIRE_ROW_FORMAT = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_RESET = enum.auto()  # keyword
    KEYWORD_RESIGNAL = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_RESOURCE = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_RESPECT = enum.auto()  # keyword : SQL_2011-N (MySQL 8.0)
    KEYWORD_RESTART = enum.auto()  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_RESTORE = enum.auto()  # keyword
    KEYWORD_RESTRICT = enum.auto()  # reserved keyword
    KEYWORD_RESUME = enum.auto()  # keyword
    KEYWORD_RETAIN = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_RETURN = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_RETURNED_SQLSTATE = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_RETURNING = enum.auto()  # keyword : SQL-2016-N (MySQL 8.0)
    KEYWORD_RETURNS = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_REUSE = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_REVERSE = enum.auto()  # keyword
    KEYWORD_REVOKE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_RIGHT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_RLIKE = enum.auto()  # reserved keyword
    KEYWORD_ROLE = enum.auto()  # keyword : SQL-1999-R (MySQL 8.0)
    KEYWORD_ROLLBACK = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_ROLLUP = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_ROTATE = enum.auto()  # keyword
    KEYWORD_ROUTINE = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_ROW = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_ROWS = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_ROW_COUNT = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_ROW_FORMAT = enum.auto()  # keyword
    KEYWORD_ROW_NUMBER = enum.auto()  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_RTREE = enum.auto()  # keyword
    KEYWORD_S3 = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SAVEPOINT = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_SCHEDULE = enum.auto()  # keyword
    KEYWORD_SCHEMA = enum.auto()  # reserved keyword
    KEYWORD_SCHEMAS = enum.auto()  # reserved keyword
    KEYWORD_SCHEMA_NAME = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_SECOND = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_SECONDARY = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SECONDARY_ENGINE = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SECONDARY_ENGINE_ATTRIBUTE = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SECONDARY_LOAD = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SECONDARY_UNLOAD = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SECOND_MICROSECOND = enum.auto()  # reserved keyword
    KEYWORD_SECURITY = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_SELECT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_SENSITIVE = enum.auto()  # reserved keyword : FUTURE-USE
    KEYWORD_SEPARATOR = enum.auto()  # reserved keyword
    KEYWORD_SERIAL = enum.auto()  # keyword
    KEYWORD_SERIALIZABLE = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_SERVER = enum.auto()  # keyword
    KEYWORD_SESSION = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_SET = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_SHARE = enum.auto()  # keyword
    KEYWORD_SHOW = enum.auto()  # reserved keyword
    KEYWORD_SHUTDOWN = enum.auto()  # keyword
    KEYWORD_SIGNAL = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_SIGNED = enum.auto()  # keyword
    KEYWORD_SIMPLE = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_SKIP = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SLAVE = enum.auto()  # keyword
    KEYWORD_SLOW = enum.auto()  # keyword
    KEYWORD_SMALLINT = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_SNAPSHOT = enum.auto()  # keyword
    KEYWORD_SOCKET = enum.auto()  # keyword
    KEYWORD_SOME = enum.auto()  # reserved keyword
    KEYWORD_SONAME = enum.auto()  # keyword
    KEYWORD_SOUNDS = enum.auto()  # keyword
    KEYWORD_SOURCE = enum.auto()  # keyword
    KEYWORD_SOURCE_AUTO_POSITION = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_BIND = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_COMPRESSION_ALGORITHM = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_CONNECT_RETRY = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_DELAY = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_HEARTBEAT_PERIOD = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_HOST = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_LOG_FILE = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_LOG_POS = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_PASSWORD = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_PORT = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_PUBLIC_KEY_PATH = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_RETRY_COUNT = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CA = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CAPATH = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CERT = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CIPHER = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CRL = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_CRLPATH = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_KEY = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_SSL_VERIFY_SERVER_CERT = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_TLS_CIPHERSUITES = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_TLS_VERSION = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_USER = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SOURCE_ZSTD_COMPRESSION_LEVEL = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_SPATIAL = enum.auto()  # reserved keyword
    KEYWORD_SPECIFIC = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_SQL = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_SQLEXCEPTION = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_SQLSTATE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_SQLWARNING = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_SQL_AFTER_GTIDS = enum.auto()  # keyword : MYSQL
    KEYWORD_SQL_AFTER_MTS_GAPS = enum.auto()  # keyword : MYSQL
    KEYWORD_SQL_BEFORE_GTIDS = enum.auto()  # keyword : MYSQL
    KEYWORD_SQL_BIG_RESULT = enum.auto()  # reserved keyword
    KEYWORD_SQL_BUFFER_RESULT = enum.auto()  # keyword
    KEYWORD_SQL_CALC_FOUND_ROWS = enum.auto()  # reserved keyword
    KEYWORD_SQL_NO_CACHE = enum.auto()  # keyword
    KEYWORD_SQL_SMALL_RESULT = enum.auto()  # reserved keyword
    KEYWORD_SQL_THREAD = enum.auto()  # keyword
    KEYWORD_SQL_TSI_DAY = enum.auto()  # keyword
    KEYWORD_SQL_TSI_HOUR = enum.auto()  # keyword
    KEYWORD_SQL_TSI_MINUTE = enum.auto()  # keyword
    KEYWORD_SQL_TSI_MONTH = enum.auto()  # keyword
    KEYWORD_SQL_TSI_QUARTER = enum.auto()  # keyword
    KEYWORD_SQL_TSI_SECOND = enum.auto()  # keyword
    KEYWORD_SQL_TSI_WEEK = enum.auto()  # keyword
    KEYWORD_SQL_TSI_YEAR = enum.auto()  # keyword
    KEYWORD_SRID = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_SSL = enum.auto()  # reserved keyword
    KEYWORD_ST_COLLECT = enum.auto()  # word (MySQL 8.0)
    KEYWORD_STACKED = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_START = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_STARTING = enum.auto()  # reserved keyword
    KEYWORD_STARTS = enum.auto()  # keyword
    KEYWORD_STATS_AUTO_RECALC = enum.auto()  # keyword
    KEYWORD_STATS_PERSISTENT = enum.auto()  # keyword
    KEYWORD_STATS_SAMPLE_PAGES = enum.auto()  # keyword
    KEYWORD_STATUS = enum.auto()  # keyword
    KEYWORD_STOP = enum.auto()  # keyword
    KEYWORD_STORAGE = enum.auto()  # keyword
    KEYWORD_STORED = enum.auto()  # reserved keyword
    KEYWORD_STRAIGHT_JOIN = enum.auto()  # reserved keyword
    KEYWORD_STREAM = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_STRING = enum.auto()  # keyword
    KEYWORD_SUBCLASS_ORIGIN = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_SUBJECT = enum.auto()  # keyword
    KEYWORD_SUBPARTITION = enum.auto()  # keyword
    KEYWORD_SUBPARTITIONS = enum.auto()  # keyword
    KEYWORD_SUBDATE = enum.auto()  # word
    KEYWORD_SUPER = enum.auto()  # keyword
    KEYWORD_SUSPEND = enum.auto()  # keyword
    KEYWORD_SWAPS = enum.auto()  # keyword
    KEYWORD_SWITCHES = enum.auto()  # keyword
    KEYWORD_SYSTEM = enum.auto()  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_TABLE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_TABLES = enum.auto()  # keyword
    KEYWORD_TABLESAMPLE = enum.auto()  # reserved keyword
    KEYWORD_TABLESPACE = enum.auto()  # keyword
    KEYWORD_TABLE_CHECKSUM = enum.auto()  # keyword
    KEYWORD_TABLE_NAME = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_TEMPORARY = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_TEMPTABLE = enum.auto()  # keyword
    KEYWORD_TERMINATED = enum.auto()  # reserved keyword
    KEYWORD_TEXT = enum.auto()  # keyword
    KEYWORD_THAN = enum.auto()  # keyword
    KEYWORD_THEN = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_THREAD_PRIORITY = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_TIES = enum.auto()  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_TIME = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_TIMESTAMP = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_TIMESTAMP_ADD = enum.auto()  # keyword
    KEYWORD_TIMESTAMP_DIFF = enum.auto()  # keyword
    KEYWORD_TINYBLOB = enum.auto()  # reserved keyword : MYSQL
    KEYWORD_TINYINT = enum.auto()  # reserved keyword : MYSQL
    KEYWORD_TINYTEXT = enum.auto()  # reserved keyword : MYSQL
    KEYWORD_TLS = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_TO = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_TRAILING = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_TRANSACTION = enum.auto()  # keyword
    KEYWORD_TRIGGER = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_TRIGGERS = enum.auto()  # keyword
    KEYWORD_TRUE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_TRUNCATE = enum.auto()  # keyword
    KEYWORD_TYPE = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_TYPES = enum.auto()  # keyword
    KEYWORD_UNBOUNDED = enum.auto()  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_UNCOMMITTED = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_UNDEFINED = enum.auto()  # keyword
    KEYWORD_UNDO = enum.auto()  # reserved keyword : FUTURE-USE
    KEYWORD_UNDOFILE = enum.auto()  # keyword
    KEYWORD_UNDO_BUFFER_SIZE = enum.auto()  # keyword
    KEYWORD_UNICODE = enum.auto()  # keyword
    KEYWORD_UNINSTALL = enum.auto()  # keyword
    KEYWORD_UNION = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_UNIQUE = enum.auto()  # reserved keyword
    KEYWORD_UNKNOWN = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_UNLOCK = enum.auto()  # reserved keyword
    KEYWORD_UNREGISTER = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_UNSIGNED = enum.auto()  # reserved keyword : MYSQL
    KEYWORD_UNTIL = enum.auto()  # keyword
    KEYWORD_UPDATE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_UPGRADE = enum.auto()  # keyword
    KEYWORD_URL = enum.auto()  # keyword (MySQL 8.0)
    KEYWORD_USAGE = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_USE = enum.auto()  # reserved keyword
    KEYWORD_USER = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_USER_RESOURCES = enum.auto()  # reserved keyword
    KEYWORD_USE_FRM = enum.auto()  # keyword
    KEYWORD_USING = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_UTC_DATE = enum.auto()  # reserved keyword
    KEYWORD_UTC_TIME = enum.auto()  # reserved keyword
    KEYWORD_UTC_TIMESTAMP = enum.auto()  # reserved keyword
    KEYWORD_VALIDATION = enum.auto()  # keyword : MYSQL
    KEYWORD_VALUE = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_VALUES = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_VARBINARY = enum.auto()  # reserved keyword : SQL-2008-R
    KEYWORD_VARCHAR = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_VARCHARACTER = enum.auto()  # reserved keyword
    KEYWORD_VARIABLES = enum.auto()  # keyword
    KEYWORD_VARYING = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_VCPU = enum.auto()  # keyword : MYSQL (MySQL 8.0)
    KEYWORD_VIEW = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_VIRTUAL = enum.auto()  # reserved keyword
    KEYWORD_VISIBLE = enum.auto()  # keyword
    KEYWORD_WAIT = enum.auto()  # keyword
    KEYWORD_WARNINGS = enum.auto()  # keyword
    KEYWORD_WEEK = enum.auto()  # keyword
    KEYWORD_WEIGHT_STRING = enum.auto()  # keyword
    KEYWORD_WHEN = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_WHERE = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_WHILE = enum.auto()  # reserved keyword
    KEYWORD_WINDOW = enum.auto()  # reserved keyword : SQL-2003-R (MySQL 8.0)
    KEYWORD_WITH = enum.auto()  # reserved keyword : SQL-2003-R
    KEYWORD_WITHOUT = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_WORK = enum.auto()  # keyword : SQL-2003-N
    KEYWORD_WRAPPER = enum.auto()  # keyword
    KEYWORD_WRITE = enum.auto()  # reserved keyword : SQL-2003-N
    KEYWORD_X509 = enum.auto()  # keyword
    KEYWORD_XA = enum.auto()  # keyword
    KEYWORD_XID = enum.auto()  # keyword : MYSQL
    KEYWORD_XML = enum.auto()  # keyword
    KEYWORD_XOR = enum.auto()  # reserved keyword
    KEYWORD_YEAR = enum.auto()  # keyword : SQL-2003-R
    KEYWORD_YEAR_MONTH = enum.auto()  # reserved keyword
    KEYWORD_ZEROFILL = enum.auto()  # reserved keyword : MYSQL
    KEYWORD_ZONE = enum.auto()  # keyword : SQL-2003-N (MySQL 8.0)
    KEYWORD_WITH_ROLLUP = enum.auto()  # INTERNAL

    # 非关键字函数
    WORD_CURDATE = enum.auto()  # MYSQL-FUNC
    WORD_CURTIME = enum.auto()  # MYSQL-FUNC
    WORD_DATE_ADD_INTERVAL = enum.auto()  # MYSQL-FUNC
    WORD_DATE_SUB_INTERVAL = enum.auto()  # MYSQL-FUNC
    WORD_EXTRACT = enum.auto()  # SQL-2003-N
    WORD_NOW = enum.auto()
    WORD_SYSDATE = enum.auto()
    WORD_BIT_AND = enum.auto()  # MYSQL-FUNC
    WORD_BIT_OR = enum.auto()  # MYSQL-FUNC
    WORD_BIT_XOR = enum.auto()  # MYSQL-FUNC
    WORD_COUNT = enum.auto()  # SQL-2003-N
    WORD_GROUP_CONCAT = enum.auto()
    WORD_JSON_ARRAYAGG = enum.auto()  # SQL-2015-R (MySQL 8.0)
    WORD_JSON_OBJECTAGG = enum.auto()  # SQL-2015-R (MySQL 8.0)
    WORD_MAX = enum.auto()  # SQL-2003-N
    WORD_MIN = enum.auto()  # SQL-2003-N
    WORD_STD = enum.auto()
    WORD_STDDEV_SAMP = enum.auto()  # SQL-2003-N
    WORD_SUM = enum.auto()  # SQL-2003-N
    WORD_VAR_SAMP = enum.auto()
    WORD_VARIANCE = enum.auto()
    WORD_SUBSTRING = enum.auto()  # SQL-2003-N
    WORD_TRIM = enum.auto()  # SQL-2003-N
    WORD_CAST = enum.auto()  # SQL-2003-R
